<html>
<header>
	<head>
		<meta charset="utf-8">
		<title>La maquette du site</title>
		<link rel="stylesheet" type="text/css" href="../vendor/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="../vendor/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="../vendor/css/styles.css">
		<script type="text/javascript" src="../vendor/js/jquery-2.1.4.min.js"></script>
		<script type="text/javascript" src="../vendor/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="../vendor/js/npm.js"></script>
	</head>
</header>