<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>        
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title">Enregistrer une nouvelle catégorie</h4>
                </div>
                <div class="panel-body">
                    <form action="/<?= PROJECT_DIRECTORY ?>dashboard/category/insert" method="post" class="form-horizontal" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Nom de la catégorie</label>
                            <div class="col-sm-10"><input name="name" class="form-control" row="5"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Ajouter la catégorie</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>