<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php 
    $c = $Categorys[0];
?>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h3>Modifier la catégorie</h3>
            <hr>
            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/category/update" method="post" class="form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name='id' value='<?= $c->id ?>'>
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Nom de la catégorie</label>
                    <div class="col-sm-10"><input name="name" class="form-control" row="5" value="<?= $c->name ?>"></div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Ajouter la catégorie</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>