<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?> 
<div id="main-wrapper">
    <div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Les catégories</h4>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">  
					<table class="table">
						<thead>
							<tr>
								<th>Nom</th>
								<th></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach ($Categorys as $Category) {
									$row = "<tr>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/category/".$Category->id."'>" . $Category->name . "</a></td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/category/".$Category->id."'><span class='fa fa-plus-square-o'></span></a></td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/category/edit/".$Category->id."'><span class='fa fa-pencil-square-o'></span></a></td>";
									$row .= "<td><a onclick='myFunction(".$Category->id.")'><span class='fa fa-times'></span></a></td></tr>";
									$row .= "</tr>";
									echo $row;
								}
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function myFunction(id) {
	    if(confirm("Etes-vous sûr de vouloir supprimer cette catégorie ? Cette action est irréversible.")) {
	    	window.location = "category/delete/"+id;
		}
	}
</script>
<?php include_once("footer.phtml"); ?>