<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>  
<?php
    $c = $Categorys[0];
?>          
<div id="main-wrapper">
    <div class="col-lg-12">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h4><?= $c->name ?></h4>
            </div>
            <div class="panel-body">
                <p>
                    <a href="<?= '/' . PROJECT_DIRECTORY . 'dashboard/category/edit/' . $c->id ?>">Modifier ce contenu.</a>
                </p>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>