<?php include_once("frontheader.phtml"); ?>

<div id="content-wrapper" class="page">
	<div class="container">
		<div class="row">
			<div class="col-md-12" id="page_cart">
				<div class="col-md-12">
					Payer
				</div>				
				<div class="col-md-12">
					<div class="order">
						<a class="btn" href="/<?= PROJECT_DIRECTORY; ?>order/paiement">Valider et payer</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php include_once("frontfooter.phtml"); ?>