<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>

<?php 
$Content = new \app\models\Content();
$fields = $Content->getFieldsName("slider");
?>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h3>Enregistrer un nouveau slide</h3>
            <hr>
            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/slider/insert" method="post" class="form-horizontal"  enctype="multipart/form-data">
                
                <?php	foreach($fields as $field): ?>
                
                <?php
                    $type = $field[0]->type;
                    $name = substr(strstr($field[0]->name, '_'), 1);
                    $value = "";
                ?>
                
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label"><?php print $field[0]->label; ?></label>
                    <div class="col-sm-10"><?php print $Content->printField($type, $name, $value, 10, 100); ?></div>
                </div>
                
                <?php endforeach; ?>
                
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Sauvegarder</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>