<form action="/<?= PROJECT_DIRECTORY ?>product/search" method="post">
    <div class="block" id="block-search">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
            </span>
            <input type="text" class="form-control" placeholder="Recherche ..." name="name">
        </div>
    </div>
</form>