<?php 
$principal = $menuModel->getMenu(1);
			
			
function RecursiveWrite($array, $first, $ul, $menuModel, $pos) {
    foreach ($array as $vals) {
    	$lastul = count($array);
    	$url = '#';
    	switch ($vals['item']->type) {
	    	case 'link' :
	    		$dir = trim(PROJECT_DIRECTORY,'/');
	    	 	$url = '/'.$dir.$vals['item']->path;
	    		break;
	    	case 'page' :
	    		$dir = trim(PROJECT_DIRECTORY,'/');
	    	 	$url = '/'.$dir.'/page/'.$vals['item']->content_id;
	    		break;
	    	case 'category' :
	    		$dir = trim(PROJECT_DIRECTORY,'/');
	    	 	$url = '/'.$dir.'/category/'.$vals['item']->content_id;
	    		break;
    	}
     	
     	if($first) {
     		echo '<li class="first-ul pull-'.$pos.' ';

	 		/* dropdown menu */
	 		if (isset($vals['children'])){	
     			echo ' dropdown">';
	 			echo '<a href="'.$url.'" class="list-title dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">'.$vals['item']->label.'<span class="caret"></span></a>';
       		} else {
		   		echo '"><a class="list-title" href="'.$url.'">'.$vals['item']->label.'</a>';
       		}
     	} else {
		 	echo '<li class="li-sub-mega"><a class="list-title" href="'.$url.'">'.$vals['item']->label.'</a>';
     	}

		
		/*
		Afficher sous menu
		*/
		if (isset($vals['children'])){	
			echo '<ul class="dropdown-menu" role="menu">';
			RecursiveWrite($vals['children'], false,1, $menuModel, null);	
			echo '</ul>';
		}
		
		echo '</li>';

    }

}
?>

<?php 
	if (!empty($principal)) {
		$i = 1;
		
		/* Séparer le menu en deux */
		$middle_principal = round(count($principal)/2);	
		$reindexed_array = array_values($principal);
		for ($i=0; $i<$middle_principal; $i++) {

			$principal_left[$i] = $reindexed_array[$i];
			unset($reindexed_array[$i]);
		}
		$principal_right = array_reverse($reindexed_array);
		
		/* Affichage du menu à gauche du logo */
		RecursiveWrite($principal_left, true, false, $menuModel,'left');
		/* Affichage du menu à droite du logo */
		RecursiveWrite($principal_right, true, false, $menuModel,'right');

	}

?>
<!--


<li class="first-ul pull-left">
	<a class="list-title" href="#">Home</a>
</li>
<li class="first-ul dropdown pull-left">
  <a href="#" class="list-title dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Shop<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li>
    	<ul>
    		<li class="list-title">Catégorie 1</li>
    		<li><a href="#">Produit 1</a></li>
    		<li><a href="#">Produit 2</a></li>
    		<li><a href="#">Produit 3</a></li>
    		<li><a href="#">Produit 4</a></li>
    	</ul>
    </li>
    <li>
    	<ul>
    		<li class="list-title">Catégorie 2</li>
    		<li><a href="#">Produit 1</a></li>
    		<li><a href="#">Produit 2</a></li>
    		<li><a href="#">Produit 3</a></li>
    		<li><a href="#">Produit 4</a></li>
    	</ul>
    </li>
    <li>
    	<ul>
    		<li class="list-title">Catégorie 3</li>
    		<li><a href="#">Produit 1</a></li>
    		<li><a href="#">Produit 2</a></li>
    		<li><a href="#">Produit 3</a></li>
    		<li><a href="#">Produit 4</a></li>
    	</ul>
    </li>
  </ul>
</li>
<li class="first-ul pull-right"><a class="list-title" href="#">About</a></li>
<li class="first-ul pull-right"><a class="list-title" href="#">Contact</a></li>
-->