<?php 

	/* Créer route pour ajouter et supprimer un produit au panier */

	$products = $Cart->cartModel->listCart(); 
	$product_res = $contentModel->getProductList();
	foreach($product_res as $pr){
		$product[$pr->content_id] = $pr;
	}
	$nb = 0;
	foreach($products as $pc) {
		$nb += $pc->quantity;
	}
/*


<form action="/<?= PROJECT_DIRECTORY; ?>product/add/3" method="post">
<button type=submit class="btn" >Add 3</button>
</form>
<form action="/<?= PROJECT_DIRECTORY; ?>product/add/4" method="post">
<button type=submit class="btn" >Add 4</button>
</form>
*/

?>
<div id="block-cart" class="block">
	(<?= $nb == 0 ? 'vide' : $nb ?>) <i class="fa fa-shopping-cart"></i>
	<a class="show_cart pointer"> Voir le panier </a>
	<div id="cart" style="display:none;">
		<?php 
		$total = 0;
		if(!empty($products)){ ?>
		<table class="tab_product">		
<?php 		foreach($products as $product_cart) {
				echo '<tr>';
				$pdt = $product[$product_cart->product_id];?>
				<td class="cart_product_line"> <a href="/<?= PROJECT_DIRECTORY; ?>product/<?=$pdt->content_id?>"><?=$pdt->content_title; ?></a> </td><td class="cart_product_line qty">x <?=  $product_cart->quantity; ?></td><td  class="cart_product_line"> <?= number_format($pdt->content_price,2,',',' ');?> €</td> <td  class="cart_product_line"> <a class="deleteproduct" data-id="<?=$product_cart->id;?>"><i class="fa fa-times"></i></a></td>
				<?php
				echo '</tr>';
				echo '<tr>';
				$total += $product_cart->quantity * $pdt->content_price;
				echo '</tr>';
			}
		
		?>
		</table>
		<div class="total"><span>TOTAL</span> : <span class="total_value"><?= number_format($total,2,',',' ') ?></span> € </div>
		<?php
		} else {
			echo 'Aucun produits';
		} ?>
		<div class="order">
		<a class="btn" href="/<?= PROJECT_DIRECTORY; ?>order">Commander</a>
		</div>
	</div> 
	<script>
		/* show cart on click */
		$('.show_cart').click(function(){
			$('#cart').fadeToggle(200);
		});
		
		/* ajax delete product */
		$('.deleteproduct').bind('click', function(){
			var id = $(this).data('id');
			var url = '/<?= PROJECT_DIRECTORY; ?>product/delete/'+id;
			$.post(window.location.origin+url).done(function() {
			    location.reload();
			});
		});
	</script>
</div>
