<li class="first-ul pull-left">
	<a class="list-title" href="#">Home</a>
</li>
<li class="first-ul dropdown pull-left">
  <a href="#" class="list-title dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Shop<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li>
    	<ul>
    		<li class="list-title">Catégorie 1</li>
    		<li><a href="#">Produit 1</a></li>
    		<li><a href="#">Produit 2</a></li>
    		<li><a href="#">Produit 3</a></li>
    		<li><a href="#">Produit 4</a></li>
    	</ul>
    </li>
    <li>
    	<ul>
    		<li class="list-title">Catégorie 2</li>
    		<li><a href="#">Produit 1</a></li>
    		<li><a href="#">Produit 2</a></li>
    		<li><a href="#">Produit 3</a></li>
    		<li><a href="#">Produit 4</a></li>
    	</ul>
    </li>
    <li>
    	<ul>
    		<li class="list-title">Catégorie 3</li>
    		<li><a href="#">Produit 1</a></li>
    		<li><a href="#">Produit 2</a></li>
    		<li><a href="#">Produit 3</a></li>
    		<li><a href="#">Produit 4</a></li>
    	</ul>
    </li>
  </ul>
</li>
<li class="first-ul pull-right"><a class="list-title" href="#">About</a></li>
<li class="first-ul pull-right"><a class="list-title" href="#">Contact</a></li>