<?php $active_pages = ['index'];
	if(strstr($_SERVER['REQUEST_URI'],'/index')){

	$slides = $contentModel->getSliderList();
	if (!empty($slides)) {
	$nb = count($slides);
?>
 
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">   
    <?php $i = 0;
  	foreach($slides as $slide) {
  	$i++; ?>
    <li data-target="#carousel-example-generic" data-slide-to="<?= $i ?>" class="<?= $i == 1 ? 'active' : ''?>"></li>    
    <?php } ?>
  </ol>

  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">
  	<?php $i = 0;
  	foreach($slides as $slide) {
  	$i ++; ?>
    <div class="item <?= $i == 1 ? 'active' : ''?>">
		<img class="img-responsive" src="/<?= PROJECT_DIRECTORY.$slide->content_path ?>" alt="<?= $slide->content_title ?>" />
      <div class="carousel-caption">
      	<h2><?= $slide->content_title ?></h2>
	  	<h3>
	  	<span><?= $slide->content_caption ?></span>
	  	</h3>

	  		<?= $slide->content_description != '' ? '<span class="desc">'.$slide->content_description.'</span>' : '' ?>
	  
	  	<a class="btn" href="/<?= PROJECT_DIRECTORY.$slide->content_link ?>">En savoir plus</a>
      </div>
    </div>
    
    <?php } ?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<?php }
} ?>