<?php 

	/* Créer route pour ajouter et supprimer un produit au panier */
	$products = array();
	if(isset($_SESSION['user'])) {
		$products = $Cart->cartModel->listCart(); 
	} else {
		if (isset($_SESSION['cart'])) {
			$products = $_SESSION['cart'];
		}
	}
	
	$product_res = $contentModel->getProductList();

	foreach($product_res as $pr){
		$product[$pr->content_id] = $pr;
	}
	
	$nb = 0;
	foreach($products as $pc) {
		$nb += $pc->quantity;
	}

?>
<div id="block-cart" class="block">
	(<?= $nb == 0 ? 'vide' : $nb ?>) <i class="fa fa-shopping-cart"></i>
	<a class="show_cart pointer"> Voir le panier </a>
	<div id="cart" style="display:none;">
		<?php 
		$total = 0;
		if(!empty($products)){ ?>
		<table class="tab_product">		
<?php 		foreach($products as $product_cart) {
					$pdt = $product[$product_cart->product_id];
				
					if($product_cart->user_content_id != 0) {
						$usc = $Cart->cartModel->getUserContent($product_cart->user_content_id);
						$price = $usc[0]->content_price;
					} else {
						$price = $pdt->content_price;
					}

					echo '<tr>';
					?>
					<td class="cart_product_line"> <a href="/<?= PROJECT_DIRECTORY; ?>product/<?=$pdt->content_id?>">
						<?=$pdt->content_title; ?></a>
					</td>
					<td class="cart_product_line qty">x <?=  $product_cart->quantity; ?></td>
					<td  class="cart_product_line" width="60px"> <?= number_format($price,2,',',' ');?> €</td> <td  class="cart_product_line"> <a class="deleteproduct" data-id="<?=$product_cart->id;?>"><i class="fa fa-times"></i></a></td>
					<?php
					echo '</tr>';
					echo '<tr>';
					$total += $product_cart->quantity * $price;
					echo '</tr>';
			}
		
		?>
		</table>
		<div class="total"><span>TOTAL</span> : <span class="total_value"><?= number_format($total,2,',',' ') ?></span> € </div>
		<?php
		} else {
			echo 'Aucun produits';
		} ?>
		<div class="order">
		<a class="btn" href="/<?= PROJECT_DIRECTORY; ?>order">Commander</a>
		</div>
	</div> 
	<script>
		/* show cart on click */
		$('.show_cart').click(function(){
			$('#cart').fadeToggle(200);
		});
		
		/* ajax delete product */
		$('.deleteproduct').bind('click', function(){
			var id = $(this).data('id');
			var url = '/<?= PROJECT_DIRECTORY; ?>cart/delete/'+id;
			console.log(window.location.origin+url);
			
			$.post(window.location.origin+url).done(function() {
			    location.reload();
			});
		});
	</script>
</div>
