<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">Edit <?= str_replace('_',' ',$Blocks->getName()); ?></h4>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="/<?= PROJECT_DIRECTORY ?>dashboard/block/update" method="post" enctype="multipart/form-data">
                         	<input type="hidden" value="<?= $Blocks->getId(); ?>" name="id" > 
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Activer</label>
                                <div class="col-sm-10">
                                    <div class="checkbox">
                                        <label>
                                            <div class="checker">
	                                            <span>
	                                            <input name="is_active" type="checkbox" <?= $Blocks->getIs_active() ? 'checked' : '' ?> value="1" >
	                                            </span>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <?php if ($Blocks->getIs_editable()) { ?>
							<div class="form-group">
                                <label class="col-sm-2 control-label">Contenu</label>
                                <div class="col-sm-10">
                                	<textarea width="100%" name="content_block"><?= $Blocks->getContent_block() ?></textarea>
                                </div>
							</div>             
							<?php } ?>               
                            <div class="row">
								<div class="col-md-12 col-sm-offset-2">
									<button class="btn btn-primary" type="submit">Sauvegarder</button>
						   		</div>
							</div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   </div>
   <?php include_once("footer.phtml"); ?>