<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
	<div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Les slides</h4>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">
					<p><a href="slider/add"><button type="button" class="btn btn-primary">Ajouter un slide</button></a></p>
					<table class="table listtable">
						<thead>
							<tr>
								<th></th>
								<th>Titre</th>
								<th>Lien</th>
								<th></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach ($Blocks as $k => $v) {

									// Vérifie si l'utilisateur est Super administrateur (1) ou administrateur (2)
									$row = "<tr>";
									$row .= '<td width="300"><div class="miniature"><img src="/'.PROJECT_DIRECTORY.$v->content_path.'"  > </div></td>';
									$row .= "<td>" . $v->content_title ."</td>";
/*
									$row .= "<td>".$v->content_caption." </td>";
									$row .= "<td>".$v->content_description." </td>";
*/
									$row .= "<td>".$v->content_link." </td>";

									$row .= "<td class='action'><a href='/" . PROJECT_DIRECTORY . "dashboard/slider/".$v->content_id."'><span class='fa fa-plus-square-o'></span></a></td>";
									$row .= "<td class='action'><a href='/" . PROJECT_DIRECTORY . "dashboard/slider/edit/".$v->content_id."'><span class='fa fa-pencil-square-o'></span></a></td>";
									$row .= "<td class='action'><a href='/" . PROJECT_DIRECTORY . "dashboard/slider/delete/".$v->content_id."'><span class='fa fa-times'></span></a></td>";
									$row .= "</tr>";
									echo $row;
								}
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>