<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
	<div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Les blocks</h4>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">  
					<table class="table">
						<thead>
							<tr>
								<th>Nom</th>
								<th>Titre</th>
								<th>Contenu Editable</th>
								<th></th>
								<th></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach ($Blocks as $k => $v) {

									// Vérifie si l'utilisateur est Super administrateur (1) ou administrateur (2)
									$row = "<tr>";
									$row .= "<th>" . ucfirst(str_replace('_',' ',str_replace('block_','',$v->name))) ."</th>";
									$row .= "<td>" . $v->title ."</td>";
									$row .= "<td>".($v->is_editable == 1 ? 'Oui' : 'Non')." </td>";
									$row .= "<td style='text-align:center'>".($v->is_active == 1 ? '<span class="label label-success">Actif</span>' : '<span class="label label-danger">Inactif</span>')." </td>";

									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/block/".$v->id."'><span class='fa fa-plus-square-o'></span></a></td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/block/edit/".$v->id."'><span class='fa fa-pencil-square-o'></span></a></td>";
									$row .= "</tr>";
									echo $row;
								}
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>