<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            

 <div id="main-wrapper">
	<div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title"><?= ucfirst(str_replace('_',' ',$Blocks->getName())); ?></h4>
			</div>
			<div class="panel-body">
				<p><b>Actif :</b> <?= $Blocks->getIs_active() ? 'Oui' : 'Non' ?></p>
				<?php if($Blocks->getContent_block() != '') { ?>
				<p><b>Contenu :</b> <?=  $Blocks->getContent_block() ?></p>
				<?php } ?>
				
				 <p>
                    <a class="btn btn-primary" href="<?= '/' . PROJECT_DIRECTORY . 'dashboard/block/edit/' . $Blocks->getId() ?>">Modifier ce contenu</a>
                </p>
			</div>
		</div>
	</div>
</div>
 <?php include_once("footer.phtml"); ?>