<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>  
<?php
    $c = $Blocks[0];
    $tags_exists = array_key_exists('tags', $c);
?>          
<div id="main-wrapper">
    <div class="col-lg-12">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h4><?= $c->content_title ?></h4>
            </div>
            <div class="panel-body">
                <div class="col-md-6"><img style="width:100%" alt="<?= $c->content_title ?>" src="<?= '/' . PROJECT_DIRECTORY . $c->content_path ?>"></div>
                <div class="col-md-6">
	                <p><b>Sous-titre :</b> <?= $c->content_caption ?></p>
	                <?= $c->content_link!= '' ? '<p><b>Lien :</b> '.$c->content_link.'</p>' : '' ?>
	                <?php if($tags_exists) { ?>
	                    <small class="label"><?= str_replace(',', ', ', $c->tags) ?></small>
	                <?php } ?>
	                <p>
	                    <a class="btn btn-primary" href="<?= '/' . PROJECT_DIRECTORY . 'dashboard/slider/edit/' . $c->content_id ?>">Modifier ce contenu</a>
	                </p>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>