<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>

<div id="main-wrapper">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-white">
			<div class="panel-heading clearfix">
                <h4 class="panel-title">Ajouter un élément de menu</h4>
           </div>
           <div class="panel-body">
				<form action="/<?= PROJECT_DIRECTORY ?>dashboard/menu/insert" method="post" enctype="multipart/form-data" class="form-horizontal">
					<!-- nom du menu -->
					<div class="form-group">
						<label class="col-md-2 control-label" for="label">Label</label>
		                <div class="col-md-10">
							<input type="text" id="label" name="label" class="form-control" placeholder="Label">
						</div>
					</div>
					<input type="hidden" value="" id="content_menu_type" name="type">
					<!-- menu -->
					<div class="form-group">
						<label class="col-md-2 control-label">Menu</label>
		                <div class="col-md-10">
							<select class="form-control" name="menu_id" >
								<option value="1" selected="selected">Principal</option>
								<option value="2">Secondaire</option>
							</select>
		                </div>
					</div>
					<!-- menu type -->
					<div class="form-group">
						<label class="col-md-2 control-label">Type d'élément</label>
		                <div class="col-md-10">
							<select class="form-control" id="content_select" >
								<option value="" selected="selected" disabled="disabled">Choisir</option>
								<option value="page">Page</option>
								<option value="category">Catégorie</option>
								<option value="link">Lien personnalisé</option>
							</select>
		                </div>
					</div>
					<!-- content menu -->
					<div class="form-group" id="content_menu" style="display:	none">
						<label class="col-md-2 control-label">Page</label>
		                <div class="col-md-10" id="items">
		                </div>
					</div>
					<div class="form-group" id="path" style="display:	none">
						<label class="col-md-2 control-label">Page</label>
		                <div class="col-md-10" id="path_item">
		                	
		                </div>
					</div>
					<!-- submit -->
                    <div class="row">
						<div class="col-md-12 col-sm-offset-2">
							<button class="btn btn-primary" type="submit">Enregistrer</button>
				   		</div>
					</div>
				</form>
		  </div>
	</div>
</div><!-- Main Wrapper -->
<script>
	$(document).ready(function(){
		$('#content_select').on('change', function() {
			var type = {type: $(this).val()}
			
			if(type.type != 'link') {
				if($('#path').length > 0) {
					$('#path_item').html('');
					$('#path').hide();							
				}
				if($('#content_menu').length > 0) {
					$('#items').html('');
				}

				$.ajax({
					url : '/<?= PROJECT_DIRECTORY ?>dashboard/menu/type', // La ressource ciblée
					type : 'POST', // Le type de la requête HTTP.
					data : type,
					dataType: 'json',
					success: function(data) {
						var html = '<select class="form-control" id="content_menu_item" name="content_id">';	
						var count = Object.keys(data).length;
						for (i=1; i <= count; i++) {
							html += '<option value="'+data[i].id+'">'+data[i].title+'</option>';
						}
						html += '</select>';
						
						$('#items').append(html);
						$('#content_menu').show();							
			       }
			    });	
			} else {
				if($('#content_menu').length > 0) {
					$('#items').html('');
					$('#content_menu').hide();							
				}
				var html = '<input id="content_menu" name="path" value="" class="form-control" placeholder="Lien"/>';	
				$('#path_item').append(html);
				$('#path').show();							

			}
			$('#content_menu_type').val(type.type);	
		});
	});
</script>
<?php include_once("footer.phtml"); ?>