<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php 
function RecursiveWrite($array, $t, &$i, $menuModel) {
 	if(!$t)
 		echo '<ul class="ullist" id="item_'.$i++.'">';

    foreach ($array as $vals) {
        echo '<li data-module="a" class="list" data-id="'.$vals['item']->id .'" data-delete="/'.PROJECT_DIRECTORY .'dashboard/menu/delete/'.$vals['item']->id .'" >';
        echo '<div>'.$vals['item']->label.'
			<i class="red delete-menu-item clickable fa fa-trash pull-right"></i>
			<i data-toggle="modal" data-target="#modal_'.$vals['item']->type .'_'.$vals['item']->id.'" class="edit-menu-item clickable fa fa-pencil pull-right"></i>
			</div>';
		if (isset($vals['children'])){	
			RecursiveWrite($vals['children'], false, $i,$menuModel);	
		}
		
		echo '<div id="modal_'. $vals['item']->type .'_'.$vals['item']->id.'" class="clickable modal fade">
		  <div class="modal-dialog">
		    <div class="modal-content">
<form action="/'. PROJECT_DIRECTORY .'dashboard/menu/update" method="post" enctype="multipart/form-data" class="form-horizontal">
		      <div class="modal-header">
		        <button type="button" class="clickable close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title">Modifier l\'élément de menu</h4>
		      </div>
		      <div class="modal-body">
				<input type="hidden" value="'.$vals['item']->id .'" name="id" >
				<div class="form-group">
					<label class="col-md-2 control-label" for="label">Label</label>
	                <div class="col-md-10">
						<input type="text" id="label" name="label" class="clickable form-control" placeholder="Label" value="'.$vals['item']->label.'">
					</div>
				</div>';
				
				if( $vals['item']->type == 'link') {
				echo '<div class="form-group" id="path">
					<label class="col-md-2 control-label">Lien</label>
	                <div class="col-md-10" id="path_item">
	                	<input type="text" class="clickable form-control" name="path" value="'.$vals['item']->path.'">
	                </div>
				</div>';
				 } else {
					$item = $menuModel->getItem($vals['item']->type, $vals['item']->content_id);
					if (!empty($item)) {
						$item = current($item);
						$name = isset($item->name) ? $item->name : $item->content_title;
					} else {
						$name = '';
					}
					echo '<div class="col-md-offset-2"> Lien vers la '. ($vals['item']->type == 'page' ? 'page' : 'catégorie' ). ' : '. $name .'</div>';
				} 
		      echo '</div>
		      <div class="modal-footer">
		        <button type="button" class="clickable btn btn-default" data-dismiss="modal">Fermer</button>
		        <button type="submit" class="clickable btn btn-primary">Sauvegarder</button>
		      </div>
</form>
		    </div>
		  </div>
		</div>';
		
		echo '</li>';
    }
	if(!$t)
    	echo '</ul>';
}

?>         
<div id="main-wrapper" class="config-menu">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-white">
				<div class="panel-heading clearfix">
					<h4 class="panel-title">Configuration du site</h4>
				</div>
				<div class="panel-body">
					<div role="tabpanel">
		                <!-- Nav tabs -->
		                <ul role="tablist" class="nav nav-tabs nav-justified">
                            <li role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/config">Informations principales</a></li>
                            <li class="active" role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/menu">Menu</a></li>
                            <li role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/emplacement">Emplacement</a></li>
                        </ul>
                        <!-- Tab panes -->
						<div class="tab-content">
							<div id="tab" class="tab-pane active fade in" role="tabpanel">
								<div class="row">
									<div class="col-md-12">
<a class="btn btn-success m-b-xs"  href="/<?= PROJECT_DIRECTORY ?>dashboard/menu/add">Ajouter un item</a>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
					                	<form class="form-horizontal" action="/<?= PROJECT_DIRECTORY ?>dashboard/menu/update" method="post" enctype="multipart/form-data">
						                	<div class="panel panel-white menu">
				                                <div class="panel-heading2">
				                                    <h3 class="panel-title">Menu principal</h3>
				                                </div>
				                                <div class="panel-body principal">
				                                	<div class="alert alert-danger" role="alert" style="display:none">
													<b>Attention ! </b> Impossible de placer l'élément ici .		
													</div>
			
													<ul id="myList" class="myList ullist listsClass" data-update="/<?=PROJECT_DIRECTORY ?>dashboard/menu/update">
														
													<?php
													$principal = $Menu->menuModel->getMenu(1);
													$secondaire = $Menu->menuModel->getMenu(2);

													$menuModel = $Menu->menuModel;
													
													if (!empty($principal)) {
														$i = 1;
														RecursiveWrite($principal, true, $i,$menuModel);
													}
													?>
														
													</ul>
				                                </div>
				                            </div>
										</form>
									</div>
									<div class="col-md-6">
					                	<form class="form-horizontal" action="/<?= PROJECT_DIRECTORY ?>dashboard/menu/update" method="post" enctype="multipart/form-data">
											<div class="panel panel-default menu">
				                                <div class="panel-heading2">
				                                    <h3 class="panel-title">Menu secondaire</h3>
				                                </div>
				                                <div class="panel-body">
				                                <div class="alert alert-danger" role="alert" style="display:none">
													<b>Attention ! </b> Impossible de placer l'élément ici .		
													</div>
			
													<ul id="myList2" class="myList ullist listsClass" data-update="/<?=PROJECT_DIRECTORY ?>dashboard/menu/update">

				                                <?php 
				                                
													if (!empty($secondaire)) {
														$i = 1;
														RecursiveWrite($secondaire, true, $i,$menuModel);
													}
				                                ?>
													</ul>
				                                </div>
				                            </div>
										</form>
									</div>
								</div>
				            </div>                
                        </div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
   <?php include_once("footer.phtml"); ?>