<div class="page-title">
    <h3>Dashboard</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <?php $name = explode('/',$_SERVER['REQUEST_URI']); ?>
            <li class="active"><?= isset($name[3]) ? ucfirst($name[3]) : '' ?></li>
        </ol>
    </div>
</div>
<?php 
if (isset($_SESSION['flash'])) {
	foreach($_SESSION['flash'] as $msg) {
		if($msg['time'] <= time()) {
			unset($_SESSION['flash']);
		} else { ?>
			<div role="alert" class="alert alert-<?= $msg['key'] ?>">
			<?= $msg['msg'] ?>
			</div>
		<?php 
		}
	}
} ?>