<div class="page-title">
    <h3>Dashboard</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </div>
</div>
<?php 
	if (isset($_SESSION['flash'])) {
		foreach($_SESSION['flash'] as $msg) { 
		?>
			<div role="alert" class="alert alert-<?= $msg['key'] ?>">
				<?= $msg['msg'] ?>
			</div>
	<?php
			if($msg['time'] <= time()) {
				unset($_SESSION['flash']);
			}
		}
	}	
?>