<?php $cms = new app\models\Config();
$cms = $cms->getConfig(); ?>
<head>
	<meta charset="utf-8">
	<title> <?= $cms->getSitename(); ?> :: Dashboard </title>
	<link rel="stylesheet" type="text/css" href="<?= VENDOR_PATH ?>css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?= VENDOR_PATH ?>css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="<?= BACK_CSS_PATH ?>modern.min.css">
	<link rel="stylesheet" type="text/css" href="<?= VENDOR_PATH ?>js/jquery-ui-1.11.4/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="<?= VENDOR_PATH ?>sortable-list/stylesheets/github-dark.css">
	<link rel="stylesheet" type="text/css" href="<?= BACK_CSS_PATH ?>styles.css">
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/jquery-ui-1.11.4/jquery-ui.min.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/npm.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/jquery.nestable.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>sortable-list/jquery-sortable-lists.js"></script>
	<script type="text/javascript" src="<?= BACK_JS_PATH ?>app.js"></script>

</head>