<head>
	<meta charset="utf-8">
	<title>La maquette du site</title>
	<link rel="stylesheet" type="text/css" href="<?= VENDOR_PATH ?>css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?= VENDOR_PATH ?>css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="<?= BACK_CSS_PATH ?>modern.min.css">
	<link rel="stylesheet" type="text/css" href="<?= BACK_CSS_PATH ?>styles.css">
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?= VENDOR_PATH ?>js/npm.js"></script>
</head>