<?php include_once("header.phtml");
	  include_once("breadcrumb.phtml"); 
	  $orderModel = new \app\models\Order();
	  $orders = $orderModel->getOrderList();
	  $userModel = new \app\models\User();
?>
            
            <div id="main-wrapper">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p class="counter"><span class="glyphicon glyphicon-user"></span><?= $nbUser ?></p>
                                    <span class="info-box-title">Nombre d'utilisateurs</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-users"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p class="counter"><span class="glyphicon glyphicon-barcode"></span><?= $nbProduct ?></p>
                                    <span class="info-box-title">Nombre de produits</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-eye"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p><span class="counter"><span class="glyphicon glyphicon-shopping-cart"></span><?= count($orders); ?></span></p>
                                    <span class="info-box-title">Nombre de ventes</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p class="counter"><span class="glyphicon glyphicon-euro"></span><?= !is_null($ttlEarnings)  ? str_replace('.',',',$ttlEarnings) : '0,00'; ?></p>
                                    <span class="info-box-title">Total des ventes</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-envelope"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- Row -->
                <div class="row">
					<div class="col-lg-12 col-md-12">
                        <div class="panel panel-white">
                            <div class="panel-heading">
                                <h4 class="panel-title">Dernières commandes</h4>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive project-stats">  
                                  <?php if(empty($orders)) {
	                                       echo '<p style="padding:20px;">Aucune commande pour le moment</p>';
                                       } else { ?>
                                  
                                   <table class="table">
                                       <thead>
                                           <tr>
                                               <th>#</th>
                                               <th>Utilisateur</th>
                                               <th>Adresse</th>
                                               <th>Montant</th>
                                           </tr>
                                       </thead>
                                       <tbody>
                                       <?php 
                                      
                                       
                                       	$i = 0;
                                       	foreach($orders as $order) { 
                                       		$i++;
	                                        $user = $userModel->getUser($order->user_id);
                                       ?>
                                           <tr>
                                               <td><?= $order->id; ?></td>
                                               <td><?= $user[0]->first_name . ' ' . $user[0]->last_name . ' (' . $user[0]->login.')'; ?></td>
                                               <td><?= $order->delivery_address; ?></td>
                                               <td><?= str_replace('.',',',$order->total_price); ?> €</td>
                                              <!--  <td><span class="label label-info">Pending</span></td> -->
                                           </tr>   
                                        <?php 
                                        if($i >= 10) { break; }
                                        } ?>                                     
										</tbody>
                                    </table>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>

				</div>
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="panel panel-white">
                            <div class="row">
                                <div class="col-sm-8">
                                    <div class="visitors-chart">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">Visiteurs</h4>
                                        </div>
                                        <div class="panel-body">
                                            <div id="flotchart1">
                                            	<canvas class="flot-base" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 811px; height: 340px;" width="811" height="340"></canvas>
												<div class="flot-text" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; font-size: smaller; color: rgb(84, 84, 84);">
													<div class="flot-x-axis flot-x1-axis xAxis x1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;">
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 19px; text-align: center;">1</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 149px; text-align: center;">2</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 279px; text-align: center;">3</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 409px; text-align: center;">4</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 538px; text-align: center;">5</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 668px; text-align: center;">6</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 798px; text-align: center;">7</div>
													</div>
													<div class="flot-y-axis flot-y1-axis yAxis y1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;">
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 314px; left: 11px; text-align: right;">0</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 252px; left: 6px; text-align: right;">20</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 190px; left: 6px; text-align: right;">40</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 127px; left: 6px; text-align: right;">60</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 65px; left: 6px; text-align: right;">80</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 3px; left: 0px; text-align: right;">100</div>
													</div>
												</div>
												<canvas class="flot-overlay" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 811px; height: 340px;" width="811" height="340"></canvas>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="stats-info">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">Statistiques</h4>
                                        </div>
                                        <div class="panel-body">
                                            <ul class="list-unstyled">
                                                <li>Utilisateurs<div class="text-success pull-right">19%<i class="fa fa-level-up"></i></div></li>
                                                <li>Produits<div class="text-success pull-right">64%<i class="fa fa-level-up"></i></div></li>
                                                <li>Internet Explorer<div class="text-danger pull-right">16%<i class="fa fa-level-down"></i></div></li>
                                                <li>Ventes<div class="text-danger pull-right">27%<i class="fa fa-level-down"></i></div></li>
                                                <li>Bénéfices<div class="text-success pull-right">34%<i class="fa fa-level-up"></i></div></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>             
                </div>
            </div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>