<?php include_once("header.phtml");
	  include_once("breadcrumb.phtml"); ?>
            
            <div id="main-wrapper">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p class="counter"><span class="glyphicon glyphicon-user"></span><?= $nbUser ?></p>
                                    <span class="info-box-title">Nombre d'utilisateurs</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-users"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p class="counter"><span class="glyphicon glyphicon-barcode"></span><?= $nbProduct ?></p>
                                    <span class="info-box-title">Nombre de produits</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-eye"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p><span class="counter"><span class="glyphicon glyphicon-shopping-cart"></span>0</span></p>
                                    <span class="info-box-title">Nombre de ventes</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel info-box panel-white">
                            <div class="panel-body">
                                <div class="info-box-stats">
                                    <p class="counter"><span class="glyphicon glyphicon-euro"></span>42</p>
                                    <span class="info-box-title">Bénéfices</span>
                                </div>
                                <div class="info-box-icon">
                                    <i class="icon-envelope"></i>
                                </div>
                                <div class="info-box-progress">
                                    <div class="progress progress-xs progress-squared bs-n">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- Row -->
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="panel panel-white">
                            <div class="row">
                                <div class="col-sm-8">
                                    <div class="visitors-chart">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">Visiteurs</h4>
                                        </div>
                                        <div class="panel-body">
                                            <div id="flotchart1">
                                            	<canvas class="flot-base" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 811px; height: 340px;" width="811" height="340"></canvas>
												<div class="flot-text" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; font-size: smaller; color: rgb(84, 84, 84);">
													<div class="flot-x-axis flot-x1-axis xAxis x1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;">
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 19px; text-align: center;">1</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 149px; text-align: center;">2</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 279px; text-align: center;">3</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 409px; text-align: center;">4</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 538px; text-align: center;">5</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 668px; text-align: center;">6</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; max-width: 101px; top: 326px; left: 798px; text-align: center;">7</div>
													</div>
													<div class="flot-y-axis flot-y1-axis yAxis y1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;">
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 314px; left: 11px; text-align: right;">0</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 252px; left: 6px; text-align: right;">20</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 190px; left: 6px; text-align: right;">40</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 127px; left: 6px; text-align: right;">60</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 65px; left: 6px; text-align: right;">80</div>
														<div class="flot-tick-label tickLabel" style="position: absolute; top: 3px; left: 0px; text-align: right;">100</div>
													</div>
												</div>
												<canvas class="flot-overlay" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 811px; height: 340px;" width="811" height="340"></canvas>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="stats-info">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">Statistiques</h4>
                                        </div>
                                        <div class="panel-body">
                                            <ul class="list-unstyled">
                                                <li>Utilisateurs<div class="text-success pull-right">69%<i class="fa fa-level-up"></i></div></li>
                                                <li>Produits<div class="text-success pull-right">224%<i class="fa fa-level-up"></i></div></li>
                                                <li>Internet Explorer<div class="text-danger pull-right">AAAAAAAAAAH%<i class="fa fa-level-down"></i></div></li>
                                                <li>Ventes<div class="text-danger pull-right">OVER 9000%<i class="fa fa-level-down"></i></div></li>
                                                <li>Bénéfices<div class="text-success pull-right">1%<i class="fa fa-level-up"></i></div></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>             
                    <div class="col-lg-12 col-md-12">
                        <div class="panel panel-white">
                            <div class="panel-heading">
                                <h4 class="panel-title">Project Stats</h4>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive project-stats">  
                                   <table class="table">
                                       <thead>
                                           <tr>
                                               <th>#</th>
                                               <th>Project</th>
                                               <th>Status</th>
                                               <th>Manager</th>
                                               <th>Progress</th>
                                           </tr>
                                       </thead>
                                       <tbody>
                                           <tr>
                                               <th scope="row">452</th>
                                               <td>Mailbox Template</td>
                                               <td><span class="label label-info">Pending</span></td>
                                               <td>David Green</td>
                                               <td>
                                               <div class="btn-group">
                                        <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            Action <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="#">Action</a></li>
                                            <li><a href="#">Another action</a></li>
                                            <li class="divider"></li>
                                            <li><a href="#">Separated link</a></li>
                                        </ul>
                                    </div>
                                               </td>
                                           </tr>
                                           <tr>
                                               <th scope="row">327</th>
                                               <td>Wordpress Theme</td>
                                               <td><span class="label label-primary">In Progress</span></td>
                                               <td>Sandra Smith</td>
                                               <td>
                                                   <div class="progress progress-sm">
                                                       <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                                       </div>
                                                   </div>
                                               </td>
                                           </tr>
                                           <tr>
                                               <th scope="row">226</th>
                                               <td>Modern Admin Template</td>
                                               <td><span class="label label-success">Finished</span></td>
                                               <td>Chritopher Palmer</td>
                                               <td>
                                                   <div class="progress progress-sm">
                                                       <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                       </div>
                                                   </div>
                                               </td>
                                           </tr>
                                           <tr>
                                               <th scope="row">178</th>
                                               <td>eCommerce template</td>
                                               <td><span class="label label-danger">Canceled</span></td>
                                               <td>Amily Lee</td>
                                               <td>
                                                   <div class="progress progress-sm">
                                                       <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                                       </div>
                                                   </div>
                                               </td>
                                           </tr>
                                           <tr>
                                               <th scope="row">157</th>
                                               <td>Website PSD</td>
                                               <td><span class="label label-info">Testing</span></td>
                                               <td>Nick Doe</td>
                                               <td>
                                                   <div class="progress progress-sm">
                                                       <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                                       </div>
                                                   </div>
                                               </td>
                                           </tr>
                                           <tr>
                                               <th scope="row">157</th>
                                               <td>Fronted Theme</td>
                                               <td><span class="label label-warning">Waiting</span></td>
                                               <td>David Green</td>
                                               <td>
                                                   <div class="progress progress-sm">
                                                       <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                                                       </div>
                                                   </div>
                                               </td>
                                           </tr>
                                       </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>