<?php include_once('head.phtml'); ?>
<style>
	.form-signin-heading{
		color: #fff;
	}
	.form-login .checkbox label {
		color: #fff;
	}
</style>
<body class="page-header-fixed pace-done">
	<main class="page-content content-wrap">
<br><br><br><br><br><br><br><br>
		<div class="col-lg-4 col-md-4"></div>
			<div class="col-lg-4 col-md-4 form-login">
				<form class="form-signin" action="/<?= PROJECT_DIRECTORY ?>dashboard/connect" method="post">
					<h2 class="form-signin-heading">Please sign in</h2>
					<label for="inputEmail" class="sr-only">Email address</label>
					<input id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" type="email" name="user[email]">
					<label for="inputPassword" class="sr-only">Password</label>
					<input id="inputPassword" class="form-control" placeholder="Password" required="" type="password" name="user[password]">
					<div class="checkbox">
						<label>
						<input value="remember-me" type="checkbox"> Remember me
						</label>
					</div>
					<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
				</form>
			</div>
			<div class="col-lg-4 col-md-4"></div>
		</main>
</body>