<div <?= !strstr('dashboard', $_SERVER['REQUEST_URI']) ? 'id="adminbar"' : ''  ?> class="navbar">
	<div class="navbar-inner">
		<div class="sidebar-pusher">
			<a href="javascript:void(0);" class="waves-effect waves-button waves-classic push-sidebar">
				<i class="fa fa-bars"></i>
			</a>
		</div>
		<div class="logo-box">
			<a href="/<?= PROJECT_DIRECTORY; ?>dashboard/index" class="logo-text"><span>Ulysse</span></a>
		</div><!-- Logo Box -->
		<div class="search-button">
			<a href="javascript:void(0);" class="waves-effect waves-button waves-classic show-search"><i class="fa fa-search"></i></a>
		</div>
		<div class="topmenu-outer">
			<div class="top-menu">
				<ul class="nav navbar-nav navbar-left">
					<li>
						<a href="/<?= PROJECT_DIRECTORY; ?>dashboard/config" class="waves-effect waves-button waves-classic"><i class="fa fa-cogs m-r-xs"></i>Configuration</a>
					</li>
					<li>
						<a href="/<?= PROJECT_DIRECTORY; ?>index" class="waves-effect waves-button waves-classic"><i class="fa fa-shopping-cart m-r-xs"></i>Voir ma boutique</a>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
<!--
						<li>	
						<a href="javascript:void(0);" class="waves-effect waves-button waves-classic show-search"><i class="fa fa-search"></i></a>
					</li>
						<li class="dropdown">
						<a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown"><i class="fa fa-envelope"></i><span class="badge badge-success pull-right">4</span></a>
						<ul class="dropdown-menu title-caret dropdown-lg" role="menu">
							<li><p class="drop-title">You have 4 new  messages !</p></li>
							<li class="dropdown-menu-list slimscroll messages">
								<ul class="list-unstyled">
									<li>
										<a href="#">
											<div class="msg-img"><div class="online on"></div></div>
											<p class="msg-name">Sandra Smith</p>
											<p class="msg-text">Hey ! I'm working on your project</p>
											<p class="msg-time">3 minutes ago</p>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="msg-img"><div class="online off"></div></div>
											<p class="msg-name">Amily Lee</p>
											<p class="msg-text">Hi David !</p>
											<p class="msg-time">8 minutes ago</p>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="msg-img"><div class="online off"></div></div>
											<p class="msg-name">Christopher Palmer</p>
											<p class="msg-text">See you soon !</p>
											<p class="msg-time">56 minutes ago</p>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="msg-img"><div class="online on"></div></div>
											<p class="msg-name">Nick Doe</p>
											<p class="msg-text">Nice to meet you</p>
											<p class="msg-time">2 hours ago</p>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="msg-img"><div class="online on"></div></div>
											<p class="msg-name">Sandra Smith</p>
											<p class="msg-text">Hey ! I'm working on your project</p>
											<p class="msg-time">5 hours ago</p>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="msg-img"><div class="online off"></div></div>
											<p class="msg-name">Amily Lee</p>
											<p class="msg-text">Hi David !</p>
											<p class="msg-time">9 hours ago</p>
										</a>
									</li>
								</ul>
							</li>
							<li class="drop-all"><a href="#" class="text-center">All Messages</a></li>
						</ul>
					</li>
-->
					<li class="dropdown">
						<a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown">
							<span class="user-name"><?= $_SESSION['user']->first_name." ".$_SESSION['user']->last_name ?><i class="fa fa-angle-down"></i></span>
							<img class="img-circle avatar" src="<?= $_SESSION['user']->avatar ? "/" . PROJECT_DIRECTORY . $_SESSION['user']->avatar : FRONT_IMG_PATH . "default_avatar.gif" ?>" width="40" height="40" alt="">
						</a>
						<ul class="dropdown-menu dropdown-list" role="menu">
							<li role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/user/<?= $_SESSION['user']->id ?>"><i class="fa fa-user"></i>Profile</a></li>
							<li role="presentation"><a href="calendar.html"><i class="fa fa-calendar"></i>Calendrier</a></li>
							<li role="presentation"><a href="inbox.html"><i class="fa fa-envelope"></i>Boîte de réception<span class="badge badge-success pull-right">4</span></a></li>
							<li role="presentation" class="divider"></li>
							<li role="presentation"><a href="lock-screen.html"><i class="fa fa-lock"></i>Lock screen</a></li>
							<li role="presentation"><a href="login.html"><i class="fa fa-sign-out m-r-xs"></i>Déconnexion</a></li>
						</ul>
					</li>
					<li>
						<a href="/<?= PROJECT_DIRECTORY ?>dashboard/logout" class="log-out waves-effect waves-button waves-classic">
							<span><i class="fa fa-sign-out m-r-xs"></i>Déconnexion</span>
						</a>
					</li>
					<li>
						<a href="javascript:void(0);" class="waves-effect waves-button waves-classic" id="showRight">
							<i class="fa fa-comments"></i>
						</a>
					</li>
				</ul><!-- Nav -->
			</div><!-- Top Menu -->
		</div>
	</div>
</div><!-- Navbar -->
						