<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<div id="main-wrapper">
	<div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">
					<img class="img-circle img-responsive" alt="" src="http://localhost/ulysse/public/admin/img/lapin-metro.png"> Serge le Lapin
				</h4>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="thumbnail">
							<h5>Coordonnées</h5>
							<ul>
								<li>Adresse 1</li>
								<li>Adresse 2</li>
								<li>Code postal</li>
								<li>Ville</li>
								<li>Pays</li>
								<li>E-mail</li>
							</ul>
						</div>
						<a class="btn btn-primary">Modifier ces informations</a>
					</div>
					<div class="col-lg-6 col-md-6">
						<div class="thumbnail">
							<h5>Produits</h5>
							<ul>
								<li>Nombre de produits proposés</li>
								<li>Nombre de produits achetés</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>

<?php
/*
	private $id;
	private $email;
	private $password;
	private $last_name;
	private $first_name;
	private $address1;
	private $address2;
	private $postal_code;
	private $city;
	private $country;
	private $path;
	private $created_date;
*/