<?php include_once("frontheader.phtml"); ?>

<div id="content-wrapper" class="page">
	<div class="container">
		<div class="row">
			<div class="col-md-12" id="page_cart">
				<div class="col-md-12">
				<h2>Choix de la livraison</h2><br>
				<div class="col-md-12">
					<form method="post" action="/<?= PROJECT_DIRECTORY; ?>order/validStep3">
					<table class="table livraison">
						<tr>
							<td width="20%">
								<img src="/<?= PROJECT_DIRECTORY ?>/public/img/la-poste.png" height="50">
							</td>
							<td>
								La poste	
							</td>
							<td width="40%">
								Livraison en 7 jours ouvrés maximum
							</td>
							<td>
								1,50 	€	
							</td>
							<td>
			                    <input id="use_address" type="checkbox" checked class="checkbox" name="livraison" value="1">
							</td>
						</tr>
						<tr>
							<td width="20%">
								<img src="/<?= PROJECT_DIRECTORY ?>/public/img/colissimo.png" height="50">
							</td>
							<td>
								Colissimo
							</td>
							<td width="40%">
								Livraison en 2/3 jours ouvrés maximum	
							</td>
								<td>
								5,40 €	
							</td>
							<td>
			                    <input id="use_address" type="checkbox" class="checkbox" name="livraison" value="2">
							</td>
						</tr>
						<tr>
							<td width="20%">
								<img src="/<?= PROJECT_DIRECTORY ?>/public/img/chronopost.png" width="130">
							</td>
							<td>
								Chronopost
							</td>
							<td width="40%">
								Livraison en 24H	
							</td>
								<td>
								10,60 €	
							</td>
							<td>
			                    <input id="use_address" type="checkbox" class="checkbox" name="livraison" value="3">
							</td>
						</tr>	
					</table>
					
					</div>
					<div class="col-md-12">
						<div class="order">
							<button type="submit" class="btn" >Valider la livraison</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php include_once("frontfooter.phtml"); ?>