<?php include_once("frontheader.phtml"); ?>
<?php 
	/* Créer route pour ajouter et supprimer un produit au panier */
	$products = $Orders;
	$product_res = $contentModel->getProductList();
	foreach($product_res as $pr){
		$product[$pr->content_id] = $pr;
	}
	$nb = 0;
	foreach($products as $pc) {
		$nb += $pc->quantity;
	}
/*


<form action="/<?= PROJECT_DIRECTORY; ?>product/add/3" method="post">
<button type=submit class="btn" >Add 3</button>
</form>
<form action="/<?= PROJECT_DIRECTORY; ?>product/add/4" method="post">
<button type=submit class="btn" >Add 4</button>
</form>
*/

?>
<div id="content-wrapper" class="page">
	<div class="container">
		<div class="row">
		
			
			<div class="col-md-12" id="page_cart">
				<h1>Panier</h1>
				<div class="col-md-12">
				<?php 
				$total = 0;
				if(!empty($products)){ ?>
				<table class="tab_product">	
					<thead>
						<td>Image</td>
						<td>Nom du produit</td>
						<td>Quantité</td>
						<td>Prix unitaire</td>
						<td>Total</td>
						<td></td>
					</thead>
						
		<?php 		foreach($products as $product_cart) {
						echo '<tr>';
						
						if($product_cart->user_content_id != 0) {
							$usc = $Cart->cartModel->getUserContent($product_cart->user_content_id);
							$price = $usc[0]->content_price;
						} else {
							$price = $pdt->content_price;
						}
						
						$pdt = $product[$product_cart->product_id];
						
						$miniature = get_miniature($pdt->content_image);
						$img = $miniature;
						?>
						<td class="cart_product_line img"> <img src="<?= $img; ?>" height="70px"></td>
						<td class="cart_product_line name"> <a href="/<?= PROJECT_DIRECTORY; ?>product/<?=$pdt->content_id?>"><?=$pdt->content_title; ?></a> </td>
						<td class="cart_product_line qty">x <?=  $product_cart->quantity; ?></td>
						<td class="cart_product_line price"> <?= number_format($price,2,',',' ');?> €</td> 
						<td class="cart_product_line"><?= number_format($price*$product_cart->quantity,2,',',' ');?> €</td>
						<td  class="cart_product_line"> <a class="deleteproduct" data-id="<?=$product_cart->id;?>"><i class="fa fa-times"></i></a></td>
						<?php
						echo '</tr>';
						$total += $product_cart->quantity * $price;	
					}
				?>
				
				<tr class="total_price">
				<td></td>
				<td></td>
				<td></td>
				<td>TOTAL </td>
				<td class="total_value"><?= number_format($total,2,',',' ') ?> € 
				<?php
				} else {
					echo 'Aucun produits';
				} ?>
				</td>
				<td></td>
				</tr>
				<tr>
				</tr>
				</table>
				
					<div class="order">
					<?php if(isset($_SESSION['user'])) { ?>
						<a class="btn" href="/<?= PROJECT_DIRECTORY; ?>order/adresse">Valider ma commande</a>
					<?php } else { ?>
						<div class="alert alert-danger" role="alert">Vous devez vous connecter pour valider votre commande.</div>
						
					<?php } ?>
					</div>

			</div>
		</div>
	</div>
</div>
<?php include_once("frontfooter.phtml"); ?>