<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-white">
				<div class="panel-heading clearfix">
                    <h4 class="panel-title">Configuration du site</h4>
               </div>
               <div class="panel-body">
					<div role="tabpanel">
		                <!-- Nav tabs -->
		                <ul role="tablist" class="nav nav-tabs nav-justified">
                            <li role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/config">Informations principales</a></li>
                            <li role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/menu">Menu</a></li>
                            <li role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/emplacement">Emplacement</a></li>
                            <li  class="active" role="presentation"><a href="/<?= PROJECT_DIRECTORY ?>dashboard/config/custom">Customiser le thème</a></li>

                        </ul>
                        <!-- Tab panes -->
						<div class="tab-content">
							<h2>Ajouter mon css</h2>
							<div id="tab" class="tab-pane active fade in" role="tabpanel">
				                <form class="form-horizontal" action="/<?= PROJECT_DIRECTORY ?>dashboard/config/customsave" method="post" enctype="multipart/form-data">
									<textarea rows=22 name="custom" class=" form-control"><?= $Configs; ?></textarea>
									<button class="btn btn-primry">Enregister</button>
				                </form>
				            </div>                
                        </div>
                                        
					</div>
				</div>
			 </div>
	        </div>
        </div>
   </div>
   <?php include_once("footer.phtml"); ?>