<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">Informations principales</h4>
                    </div>
					<?php 
						if ($Configs->getLogo() != '' && !is_null($Configs->getLogo()) ) { ?>
					<div class="row">
						<div class="col-md-12 col-sm-offset-2">
	                    	<img src="/<?= PROJECT_DIRECTORY.$Configs->getLogo(); ?>" />
						</div>
					</div>
                    <?php } ?>
                    <div class="panel-body">
                        <form class="form-horizontal" action="/<?= PROJECT_DIRECTORY ?>dashboard/config/update" method="post" enctype="multipart/form-data">
                         	<input type="hidden" value="<?= $Configs->getId() ?>" name="id"?> 
                         	<div class="form-group">
                                <label class="col-sm-2 control-label" for="input-placeholder">Logo</label>
                                <div class="col-sm-10">
                                    <input type="file" placeholder="Logo" name="logo" id="input-placeholder" class="form-control">
                                </div>
                            </div> 
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-Default">Nom du site</label>
                                <div class="col-sm-10">
                                    <input type="text" id="input-Default" class="form-control" placeholder="Sitename" name="sitename" value="<?= $Configs->getSitename() ?>" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-Default">Slogan</label>
                                <div class="col-sm-10">
                                    <input type="text" id="input-Default" class="form-control" placeholder="Slogan" name="slogan" value="<?= $Configs->getSlogan() ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-placeholder">Copyright</label>
                                <div class="col-sm-10">
                                    <input type="text" placeholder="Copyright" name="copyright" id="input-placeholder" class="form-control" value="<?= $Configs->getCopyright() ?>">
                                </div>
                            </div> 
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Activer la maintenance</label>
                                <div class="col-sm-10">
                                    <div class="checkbox">
                                        <label>
                                            <div class="checker"><span><input type="checkbox" <?= $Configs->getIs_maintenance() ? 'checked' : '' ?> ></span></div>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
								<div class="col-md-12 col-sm-offset-2">
									<button class="btn btn-primary" type="submit">Sauvegarder</button>
						   		</div>
							</div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   </div>