<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<?php
	$u = $Users[0];
?>
<div id="main-wrapper">
	<div class="panel-body">
		<form <?php /*action="/<?= PROJECT_DIRECTORY ?>dashboard/user/update"*/ ?> method="post" enctype="multipart/form-data" class="form-horizontal">
			<!-- email -->
			<div class="form-group">
				<label for="email">E-mail</label>
				<input type="text" id="email" name="email" class="form-control" placeholder="E-mail" value = "<?= $u ? $u->email : '' ?>">
			</div>
			<!-- login -->
			<div class="form-group">
				<label for="login">Login</label>
				<input type="text" id="login" name="login" class="form-control" placeholder="Login" value = "<?= $u ? $u->login : '' ?>">
			</div>
			<!-- password -->
			<div class="form-group">
				<label for="password">Mot de passe</label>
				<input type="text" id="password" name="password" class="form-control" placeholder="Mot de passe">
			</div>
			<!-- first-name -->
			<div class="form-group">
				<label for="first_name">Prénom</label>
				<input type="text" id="first_name" name="first_name" class="form-control" placeholder="Prénom" value = "<?= $u ? $u->first_name : '' ?>">
			</div>
			<!-- last-name -->
			<div class="form-group">
				<label for="last_name">Nom</label>
				<input type="text" id="last_name" name="last_name" class="form-control" placeholder="Nom" value = "<?= $u ? $u->last_name : '' ?>">
			</div>
			<!-- address-1 -->
			<div class="form-group">
				<label for="address1">Adresse</label>
				<input type="text" id="address1" name="address1" class="form-control" placeholder="Adresse" value = "<?= $u ? $u->address1 : '' ?>">
			</div>
			<!-- address-2 -->
			<div class="form-group">
				<label for="address2">Complément</label>
				<input type="text" id="address2" name="address2" class="form-control" placeholder="Complément de l'adresse" value = "<?= $u ? $u->address2 : '' ?>">
			</div>
			<!-- postal-code -->
			<div class="form-group">
				<label for="postal_code">Code postal</label>
				<input type="text" id="postal_code" name="postal_code" class="form-control" placeholder="Code postal" value = "<?= $u ? $u->postal_code : '' ?>">
			</div>
			<!-- city -->
			<div class="form-group">
				<label for="city">Ville</label>
				<input type="text" id="city" name="city" class="form-control" placeholder="Ville" value = "<?= $u ? $u->city : '' ?>">
			</div>
			<!-- country -->
			<div class="form-group">
				<label for="country">Pays</label>
				<input type="text" id="country" name="country" class="form-control" placeholder="Pays" value = "<?= $u ? $u->country : '' ?>">
			</div>
			<!-- submit -->
			<div class="form-group">
				<input type="button" id="submit" name="submit" class="form-control" value = "Enregistrer">
			</div>
		</form>
	</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>