<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<?php
	$u = $Users[0];
?>
<div id="main-wrapper">
	<div class="row">
        <div class="col-md-12">
        	<div class="panel panel-white">
        		<div class="panel-heading clearfix">
					<h4 class="panel-title">Editer un utilisateur</h4>
				</div>
				<div class="panel-body">
					<form action="/<?= PROJECT_DIRECTORY ?>dashboard/user/update" method="post" enctype="multipart/form-data" class="form-horizontal">
						<input type="hidden" name="id" id="id" value="<?= $u->id ?>">

						<!-- email -->
						<div class="form-group">
							<label for="email" class="col-sm-2 control-label">E-mail</label>
							<div class="col-sm-10"><input type="text" id="email" name="email" class="form-control" placeholder="E-mail" value = "<?= $u ? $u->email : '' ?>"></div>
						</div>

						<!-- login -->
						<div class="form-group">
							<label for="login" class="col-sm-2 control-label">Login</label>
							<div class="col-sm-10"><input type="text" id="login" name="login" class="form-control" placeholder="Login" value = "<?= $u ? $u->login : '' ?>"></div>
						</div>

						<!-- password -->
						<div class="form-group">
							<label for="password" class="col-sm-2 control-label">Mot de passe</label>
							<div class="col-sm-10"><input type="password" id="password" name="password" class="form-control" placeholder="Mot de passe"></div>
						</div>

						<!-- avatar -->
						<?php if ($u->avatar != '' && !is_null($u->avatar) ) { ?>
							<input type="hidden" value="<?= $u->avatar ?>" name="old_avt" >
						<?php } ?>

						<div class="form-group">
							<label for="avatar" class="col-sm-2 control-label">Avatar</label>
							<div class="col-sm-10"><input type="file" placeholder="Avatar" name="avatar" id="avatar" class="form-control"></div>
						</div> 

						<!-- first-name -->
						<div class="form-group">
							<label for="first_name" class="col-sm-2 control-label">Prénom</label>
							<div class="col-sm-10"><input type="text" id="first_name" name="first_name" class="form-control" placeholder="Prénom" value = "<?= $u ? $u->first_name : '' ?>"></div>
						</div>

						<!-- last-name -->
						<div class="form-group">
							<label for="last_name" class="col-sm-2 control-label">Nom</label>
							<div class="col-sm-10"><input type="text" id="last_name" name="last_name" class="form-control" placeholder="Nom" value = "<?= $u ? $u->last_name : '' ?>"></div>
						</div>

						<!-- address-1 -->
						<div class="form-group">
							<label for="address1" class="col-sm-2 control-label">Adresse</label>
							<div class="col-sm-10"><input type="text" id="address1" name="address1" class="form-control" placeholder="Adresse" value = "<?= $u ? $u->address1 : '' ?>"></div>
						</div>

						<!-- address-2 -->
						<div class="form-group">
							<label for="address2" class="col-sm-2 control-label">Complément</label>
							<div class="col-sm-10"><input type="text" id="address2" name="address2" class="form-control" placeholder="Complément de l'adresse" value = "<?= $u ? $u->address2 : '' ?>"></div>
						</div>

						<!-- postal-code -->
						<div class="form-group">
							<label for="postal_code" class="col-sm-2 control-label">Code postal</label>
							<div class="col-sm-10"><input type="text" id="postal_code" name="postal_code" class="form-control" placeholder="Code postal" value = "<?= $u ? $u->postal_code : '' ?>"></div>
						</div>

						<!-- city -->
						<div class="form-group">
							<label for="city" class="col-sm-2 control-label">Ville</label>
							<div class="col-sm-10"><input type="text" id="city" name="city" class="form-control" placeholder="Ville" value = "<?= $u ? $u->city : '' ?>"></div>
						</div>

						<!-- country -->
						<div class="form-group">
							<label for="country" class="col-sm-2 control-label">Pays</label>
							<div class="col-sm-10"><input type="text" id="country" name="country" class="form-control" placeholder="Pays" value = "<?= $u ? $u->country : '' ?>"></div>
						</div>

						<!-- user role -->
						<div class="form-group">
							<label class="col-sm-2 control-label">Role de l'utilisateur</label>
							<?php
								$req = new \config\database();
								$result = $req->pdo->query("SELECT * FROM role ORDER BY id DESC")->fetchAll(\PDO::FETCH_OBJ);
							?>
							<div class="col-sm-10"><select class="form-control" id="role_id" name="role_id">
								<?php
									foreach ($result as $v) {
										$opt = "<option value='" . $v->id . "' ";
										if($u->role_id == $v->id) {
											$opt .= "selected='selected'";
										}
										$opt .= ">";
										if($v->id == 1) {
											$opt .= "Super administrateur";
										} else {
											$opt .= ucfirst($v->name);
										}
										$opt .= "</option>";
										echo $opt;
									}
								?>
							</select></div>
						</div>

						<!-- submit -->
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10"><button class="btn btn-primary" type="submit">Sauvegarder</button></div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>