<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<?php
	$u = $Users[0];
?>
<div id="main-wrapper">
	<form method="POST" action="">
		<!-- email -->
		<div class="input-group">
			<label for="email">E-mail</label>
			<input type="text" id="email" name="email" class="form-control" placeholder="Username">
		</div>
		<!-- login -->
		<div class="input-group">
			<label for="login">Login</label>
			<input type="text" id="login" name="login" class="form-control" placeholder="Username">
		</div>
		<!-- password -->
		<div class="input-group">
			<label for="password">Mot de passe</label>
			<input type="text" id="password" name="password" class="form-control" placeholder="Username">
		</div>
		<!-- first-name -->
		<div class="input-group">
			<label for="first_name">Prénom</label>
			<input type="text" id="first_name" name="first_name" class="form-control" placeholder="Username">
		</div>
		<!-- last-name -->
		<div class="input-group">
			<label for="last_name">Nom</label>
			<input type="text" id="last_name" name="last_name" class="form-control" placeholder="Username">
		</div>
		<!-- address-1 -->
		<div class="input-group">
			<label for="address1">Adresse</label>
			<input type="text" id="address1" name="address1" class="form-control" placeholder="Username">
		</div>
		<!-- address-2 -->
		<div class="input-group">
			<label for="address2">Complément</label>
			<input type="text" id="address2" name="address2" class="form-control" placeholder="Username">
		</div>
		<!-- postal-code -->
		<div class="input-group">
			<label for="postal_code">Code postal</label>
			<input type="text" id="postal_code" name="postal_code" class="form-control" placeholder="Username">
		</div>
		<!-- city -->
		<div class="input-group">
			<label for="city">Ville</label>
			<input type="text" id="city" name="city" class="form-control" placeholder="Username">
		</div>
		<!-- country -->
		<div class="input-group">
			<label for="country">Pays</label>
			<input type="text" id="country" name="country" class="form-control" placeholder="Username">
		</div>
	</form>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>