<?php include_once('frontheader.phtml');?>
		<div id="content-wrapper" class="page">
			<div class="container">
				<div class="row">
					<div class="col-md-offset-3	 col-md-6">
					     <form class="form-signin" action="/<?= PROJECT_DIRECTORY ?>register/insert" method="post">
					        <h1 class="form-signin-heading">S'enregistrer</h1>
							<label for="inputLogin" class="control-label">Identifiant</label>
					        <input id="inputLogin" class="form-control" placeholder="Identifiant" required="" autofocus="" name="login" type="text">
							<label for="inputFirstname" class="control-label">Prénom</label>
					        <input id="inputFirstname" class="form-control" placeholder="Prénom" required="" autofocus="" name="last_name" type="text">
					        
					        <label for="inputLastname" class="control-label">Nom </label>
					        <input id="inputLastname" class="form-control" placeholder="Nom" required="" autofocus=""  name="first_name"  type="test">
					
					        <label for="inputEmail" class="control-label">Email </label>
					        <input id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" type="email" name="email">
					        <label for="inputPassword" class="control-label">Mot de passe</label>
					        <input id="inputPassword" class="form-control" placeholder="Password" required="" type="password" name="password">
					        <button class="btn btn-primary" type="submit">Inscription</button>
					    </form>
					</div>
				</div>
			</div> <!-- /container -->
<?php include_once('frontfooter.phtml');?>
