<?php include_once("frontheader.phtml"); ?>
<?php
	$u 		= $Users[0];
	$orders = $User->orderModel->getUserOrder($id);
	$buys   = $User->orderModel->getUserBuys($id);
	$products = $User->contentModel->getUserProduct($id);
?>
<!-- CONTENT -->
	<div id="content-wrapper" class="user">
		<div class="container">
			<div class="row">
				<div class="col-md-12" id="article_list">
					<div class="profile-image">
                        <img src="<?= get_avatar($u->avatar); ?>" alt="">
                    </div>
                    <h3 class="text-center"><?= $u->first_name && $u->last_name ? $u->first_name . " " . $u->last_name : $u->login ?></h3>
                    <ul class="list-unstyled text-center">
                        <li><p><i class="fa fa-map-marker m-r-xs"></i>
                        	<?php 
                        		$completAddress = $u->address1 && $u->address2 ? $u->address1 . " / " . $u->address2 : "Adresse non renseignée";
                        		$completAddress .= "<br>";
                        		$completAddress .= $u->postal_code && $u->city ? $u->postal_code . " " . $u->city : "";
                        		$completAddress .= $u->postal_code && $u->city && $u->country ? ", " : "";
                        		$completAddress .= $u->country ? $u->country : "";
                        		echo $completAddress;
                        	?>
                        </p>
                        </li>
                        <li><p><i class="fa fa-envelope m-r-xs"></i><a href="mailto:<?= $u->email ?>"><?= $u->email ?></a></p></li>
                        <?php if($_SESSION['user']->id == $u->id) { ?>
                            <li><p><a href="edit/<?= $u->id ?>">Modifier votre profil</a></p></li>
                        <?php } ?>
                        <hr>
                    </ul>
				</div>
				<div class="col-md-6">
					<h2>Vos commandes</h2>
					<br>
                    <table class="table adminorder">
					<?php 
					$i = 0;
					foreach($orders as $order) {
						$i++;
						$pdt = $User->contentModel->getProduct($order->product_id);
						$pdt = current($pdt['results']); ?>
					   	<tr>
						   	<td><?= $pdt->content_title ?></td>
						   	<td>x<?=$order->quantity ?> </td>
						   	<td><?= $pdt->content_price ?> €</td>
						   	<td>
						   	<a href="/<?= PROJECT_DIRECTORY ?>dashboard/order/<?= $order->id ?>">
								<span class="fa fa-plus-square-o"></span>
							</a>
							</td>
						</tr>
						
                      <?php 
                      if($i >= 3) { break; }
                      } ?>
                    </table>
                    <div style="text-align:center;">
                    	<a href="/<?= PROJECT_DIRECTORY ?>dashboard/orders" class="btn btn-success">Voir toutes mes commandes</a>
					</div>
				</div>
				<div class="col-md-6">
					<h2>Vos achats</h2>
                    <br>
                    <table class="table adminorder">
						<?php 
						$i = 0;
						foreach($buys as $buy) {
							$i++;
							$pdt = $User->contentModel->getProduct($buy->product_id);
							$pdt = current($pdt['results']); ?>
						   	<tr>
							   	<td><?= $pdt->content_title ?></td>
							   	<td>x<?=$buy->quantity ?> </td>
							   	<td><?= $pdt->content_price ?> €</td>
							</tr>
							
                          <?php 
                          if($i >= 3) { break; }
                        } ?>
                        </table>
                    <div style="text-align:center;">
                        <a href="/<?= PROJECT_DIRECTORY ?>dashboard/orders" class="btn btn-success">Voir tous mes achats</a>
                    </div>
				</div>
				<div style="margin-top:50px;" class="col-md-12 m-t-lg">
				 
					<h2>Vos produits</h2>
	                    
	            	<?php if(!empty($products)) {
	            		foreach($products as $product) {
	            			$p = $product['results'][0];
	            			
	            			$row = "<div class='p_row " . strtolower($p->category_name) . " data-category=" . strtolower($p->category_name) . "'>";
							$row .= "<div class='product_photo'>";
							$row .= "<img src='" . get_miniature($p->content_image) . "' alt='" . $p->content_title . "'>";
							$row .= "</div>";
							$row .= "<div class='product_details'>";
							$row .= "<a href='/" . PROJECT_DIRECTORY . "product/".$p->content_id."'></a>";
							$row .= "<h2>" . $p->content_title . "</h2>";
							$row .= "<div>" . $p->content_price . " €</div>";
							$row .= "</div>";
							if(!$p->content_active) {
							$row .= '<div class="edit"><a class="btn" href="/'.PROJECT_DIRECTORY.'user/product/edit/'.$p->content_id.'"> Edit </a></div>';
							}
							$row .= "</div>";
							echo $row;
						
	            			} 
		            	}
	            	?>
                	</div>
                </div>
			</div>
		</div>
	</div>
<?php include_once("frontfooter.phtml"); ?>