<?php include_once("frontheader.phtml"); ?>
<?php
	$id = $_SESSION['user']->id;
	$u 		 = $Users[0];
	$buys   = $User->orderModel->getUserBuys($id);
	$products = $User->contentModel->getUserProduct($id);
?>
<!-- CONTENT -->
	<div id="content-wrapper" class="user">
		<div class="container">
			<div class="row">
				<div class="col-md-12" id="article_list">
					<div class="profile-image">
                        <img src="<?= get_avatar($u->avatar); ?>" alt="">
                    </div>
                    <h3 class="text-center"><?= $u->first_name && $u->last_name ? $u->first_name . " " . $u->last_name : $u->login ?></h3>
                    <ul class="list-unstyled text-center">
                        <li><p><i class="fa fa-map-marker m-r-xs"></i>
                        	<?php 
                        		$completAddress = $u->address1 && $u->address2 ? $u->address1 . " / " . $u->address2 : "Adresse non renseignée";
                        		$completAddress .= "<br>";
                        		$completAddress .= $u->postal_code && $u->city ? $u->postal_code . " " . $u->city : "";
                        		$completAddress .= $u->postal_code && $u->city && $u->country ? ", " : "";
                        		$completAddress .= $u->country ? $u->country : "";
                        		echo $completAddress;
                        	?>
                        </p>
                        </li>
                        <li><p><i class="fa fa-envelope m-r-xs"></i><a href="mailto:<?= $u->email ?>"><?= $u->email ?></a></p></li>
                        <?php if($_SESSION['user']->id == $u->id) { ?>
                            <li><p><a href="edit/<?= $u->id ?>">Modifier votre profil</a></p></li>
                        <?php } ?>
                        <hr>
                    </ul>
				</div>
				<div class="col-md-12">
					<h2>Vos achats</h2>
                    <br>
                    <table class="table adminorder">
						<?php 
						foreach($buys as $buy) {
							$pdt = $User->contentModel->getProduct($buy->product_id);
							$pdt = current($pdt['results']); 
							
							switch($buy->status_id) {
								case 1:
									$status = '<span class="label label-success">Envoyé</span>';
									break;
								default:
									$status = '<span class="label label-default">En cours</span>';
									break;
							}
							
							if($buy->user_content_id != 0) {
								$usc = $Cart->cartModel->getUserContent($buy->user_content_id);
								$price = $usc[0]->content_price;
							} else {
								$price = $pdt->content_price;
							}
							?>
						   	<tr>
							   	<td width=15%><img height=70 src="<?= get_avatar($pdt->content_image) ?>"></td>
							   	<td width=35%><?= $pdt->content_title ?></td>
							   	<td>x<?=$buy->quantity ?> </td>
							   	<td><?= $price ?> €</td>
							   	<td><?= $status ?> </td>
							</tr>
							
                          <?php 
                        } 
                        if(empty($buys)) {
							echo '<p style="border:1px solid #f0f0f0; padding:15px">Aucun achat en cours<p>';
						}
?>
                        </table>
	                  
				</div>
			</div>
		</div>
	</div>
<?php include_once("frontfooter.phtml"); ?>