<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<div id="main-wrapper">
	<div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Les utilisateurs</h4>
			</div>
			<div class="panel-body">
				<div class="legend">
					<p>
						<span class="badge badge-super-admin">.</span> <span class="legend-text">Super administrateur</span>
						<span class="badge badge-admin">.</span> <span class="legend-text">Administrateur</span>
					</p>
				</div>
				<div class="table-responsive list-user">  
					<table class="table">
						<thead>
							<tr>
								<th>Identifiant</th>
								<th>Login</th>
								<th>E-mail</th>
								<th>Nom</th>
								<th>Adresse</th>
								<th>Code postal</th>
								<th>Ville</th>
								<th>Date de création</th>
								<th></th>
								<?php if ($_SESSION['user']->role_id == 1 || $_SESSION['user']->role_id == 2) { ?>
									<th></th>
									<th></th>
								<?php } ?>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach ($Users as $k => $v) {

									// Vérifie si l'utilisateur est Super administrateur (1) ou administrateur (2)
									if($v->role_id == 1) {
										$row = "<tr class='success'>";
									} elseif($v->role_id == 2) {
										$row = "<tr class='info'>";
									} else {
										$row = "<tr>";
									}

									$row .= "<th>" . $v->id . "</th>";
									$row .= "<th><a href='/" . PROJECT_DIRECTORY . "dashboard/user/".$v->id."'>" . $v->login . "</a></th>";
									$row .= "<th>" . $v->email . "</th>";
									$row .= "<td>" . $v->first_name . " " . $v->last_name."</td>";
									$row .= "<td>" . $v->address1 . "</td>";
									$row .= "<td>" . $v->postal_code . "</td>";
									$row .= "<td>" . $v->city . "</td>";
									$row .= "<td>".$v->created_date."</td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/user/".$v->id."'><span class='fa fa-plus-square-o'></span></a></td>";
									if ($_SESSION['user']->role_id == 1 || $_SESSION['user']->role_id == 2) {
										$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/user/edit/".$v->id."'><span class='fa fa-pencil-square-o'></span></a></td>";
										$row .= "<td><a onclick='myFunction(".$v->id.")'><span class='fa fa-times'></span></a></td></tr>";
									}
									$row .= "</tr>";
									echo $row;

								}
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div><!-- Main Wrapper -->
<script type="text/javascript">
	function myFunction(id) {
	    if(confirm("Etes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréversible.")) {
	    	window.location = "delete/"+id;
		}
	}
</script>
<?php include_once("footer.phtml"); ?>