<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<?php
	$u = $Users[0];
?>
<div id="main-wrapper">
		<div class="profile-user">
			<div class="profile-cover">
	            <div class="row">
	                <div class="col-md-3 profile-image">
	                    <div class="profile-image-container">
	                        <img src="<?= BACK_IMG_PATH . "lapin-metro.png" ?>" alt="">
	                    </div>
	                </div>
	            </div>
	        </div>
	        <div id="main-wrapper">
	            <div class="row">
	                <div class="col-md-3 user-profile">
	                    <h3 class="text-center"><?= $u->first_name . " " . $u->last_name ?></h3>
	                    <hr>
	                    <ul class="list-unstyled text-center">
	                        <li><p><i class="fa fa-map-marker m-r-xs"></i>
	                        	<?= $u->address1 . "<br>" . $u->postal_code . " " . $u->city . ", " . $u->country ?></p>
	                        </li>
	                        <li><p><i class="fa fa-envelope m-r-xs"></i><a href="mailto:<?= $u->email ?>"><?= $u->email ?></a></p></li>
	                        <?php if($_SESSION['user']->role_id == 1 || $_SESSION['user']->role_id == 2) { ?>
	                        	<li><a href="/<?= PROJECT_DIRECTORY ?>dashboard/user/edit/<?= $u->id ?>">Modifier cet utilisateur</a></li>
	                        <?php } ?>
	                    </ul>
	                </div>
	                <div class="col-md-6 m-t-lg">
	                </div>
	                <div class="col-md-3 m-t-lg">
	                </div>
	            </div>
	        </div>
		</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>