<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<?php
$u        = $Users[0];	

/* Commande qui te sont passées */
$orders   = $User->orderModel->getUserOrder($id);

/* Tes achats */
$buys     = $User->orderModel->getUserBuys($id);
$products = $User->contentModel->getUserProduct($id);

?>
<div id="main-wrapper">
		<div class="profile-user">
			<div class="profile-cover">
	            <div class="row">
	                <div class="col-md-4 profile-image">
	                    <div class="profile-image-container">
	                        <img src="<?= get_avatar($u->avatar); ?>" alt="">
	                    </div>
	                </div>
	            </div>
	        </div>
	        <div id="main-wrapper">
	            <div class="row">
	                <div class="col-md-4 user-profile">
	                    <h3 class="text-center"><?= $u->first_name && $u->last_name ? $u->first_name . " " . $u->last_name : $u->login ?></h3>
	                    <hr>
	                    <ul class="list-unstyled text-center">
	                        <li><p><i class="fa fa-map-marker m-r-xs"></i>
	                        	<?php 
	                        		$completAddress = $u->address1 && $u->address2 ? $u->address1 . " / " . $u->address2 : "Adresse non renseignée";
	                        		$completAddress .= "<br>";
	                        		$completAddress .= $u->postal_code && $u->city ? $u->postal_code . " " . $u->city : "";
	                        		$completAddress .= $u->postal_code && $u->city && $u->country ? ", " : "";
	                        		$completAddress .= $u->country ? $u->country : "";
	                        		echo $completAddress;
	                        	?>
	                        </p>
	                        </li>
	                        <li><p><i class="fa fa-envelope m-r-xs"></i><a href="mailto:<?= $u->email ?>"><?= $u->email ?></a></p></li>
	                        <?php if($_SESSION['user']->role_id == 1 || $_SESSION['user']->role_id == 2) { ?>
	                        	<li><a href="/<?= PROJECT_DIRECTORY ?>dashboard/user/edit/<?= $u->id ?>">Modifier cet utilisateur</a></li>
	                        <?php } ?>
	                    </ul>
	                </div>
		            <div class="col-md-8 m-t-lg user-product">
		           		<div class="panel panel-default panel-transparent">
		                	<div class="panel-heading bg-white">
								<h3 class="panel-title">Vos produits</h3>
		                    </div>
		                    <div class="panel-body">
				            	<?php if(!empty($products)) {
				            		foreach($products as $product) {
				            			$product = current($product['results']);
				            			echo '
				            			<div class="col-md-3 text-center p_row">
				            			<div class="product_photo">
				            			<img height="150px" src="'.get_miniature($product->content_image).'" />
				            			</div>
				            			<div class="product_details">
				            			<a href="/'.PROJECT_DIRECTORY.'dashboard/product/'.$product->content_id.'">
				            			<h4>'. $product->content_title .'</h4>
				            			</a>
				            			</div>
				            			</div>';
				            			} 
					            	}
				            	?>
							</div>
	                	</div>
	                </div>
	                <div class="col-md-12 m-t-lg">
	                	<div class="panel panel-default panel-transparent">
		                	<div class="panel-heading bg-white">
								<h3 class="panel-title">Vos commandes</h3>
		                    </div>
		                    <div class="panel-body">
		                        <table class="table adminorder">
								<?php 
								$i = 0;
								foreach($orders as $order) {
									$i++;
									$pdt = $User->contentModel->getProduct($order->product_id);
									$pdt = current($pdt['results']); 
									switch($order->delivery_status_id) {
										case 1:
											$status = '<span class="label label-info">Envoyée</span>';
											break;
										case 2:
											$status = '<span class="label label-success">Reçue</span>';
											break;
										case 3:
											$status = '<span class="label label-danger">Annulée</span>';
											break;
										default:
											$status = '<span class="label label-primary">En cours</span>';
											break;
									}
									?>
								   	<tr>
									   	<td><?= $pdt->content_title ?></td>
									   	<td>x<?=$order->quantity ?> </td>
									   	<td><?= $pdt->content_price ?> €</td>
									   	<td><?= $status ?></td>
									   	<td>
									   	<a href="/<?= PROJECT_DIRECTORY ?>dashboard/order/<?= $order->id ?>">
											<span class="fa fa-plus-square-o"></span>
										</a>
										</td>
									</tr>
									
		                          <?php 
		                          if($i >= 3) { break; }
		                          } ?>
		                        </table>
		                        <div style="text-align:center;">
		                        	<a href="/<?= PROJECT_DIRECTORY ?>dashboard/orders/<?= $u->id ?>" class="btn btn-success">Voir toutes mes commandes</a>
								</div>
		                    </div>
		                </div>

	                </div>
	                <div class="col-md-12 m-t-lg">
		            	<div class="panel panel-default panel-transparent">
		                	<div class="panel-heading bg-white">
								<h3 class="panel-title">Vos achats</h3>
		                    </div>
		                    <div class="panel-body">
		                        <table class="table adminorder">
								<?php 
								$i = 0;
								foreach($buys as $buy) {
									$i++;
									$pdt = $User->contentModel->getProduct($buy->product_id);
									$pdt = current($pdt['results']); ?>
								   	<tr>
									   	<td><?= $pdt->content_title ?></td>
									   	<td>x<?=$buy->quantity ?> </td>
									   	<td><?= $pdt->content_price ?> €</td>
									</tr>
									
		                          <?php 
		                          if($i >= 3) { break; }
		                        } ?>
		                        </table>
		                        <div style="text-align:center;">
		                        	<a href="/<?= PROJECT_DIRECTORY ?>dashboard/buys" class="btn btn-success">Voir tous mes achats</a>
								</div>
		                    </div>
		                </div>
		            </div>
	            </div>
	        </div>
		</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>