<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<div id="main-wrapper">
<div class="col-lg-12 col-md-12">
<?php
	$id = $_SESSION['user']->id;
	$u 		 = $Users[0];
	$order = $Users['order'][0];
	$products = $User->contentModel->getUserProduct($id);
?>
<!-- CONTENT -->
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Vos commandes</h4>
			</div>

			<div class="panel-body">
        
								<div class="col-md-12">
					<h2>Votre commande</h2>
					<br>
					<?php 

						$pdt = $User->contentModel->getProduct($order->product_id);
						$pdt = current($pdt['results']); 
						
						
						if($order->user_content_id != 0) {
							$usc = $User->cartModel->getUserContent($order->user_content_id);
							$price = $usc[0]->content_price;
						} else {
							$price = $pdt->content_price;
						}
						switch($order->status_id) {
							case 1:
								$status = '<span class="label label-success">Envoyé</span>';
								break;
							default:
								$status = '<span class="label label-default">En cours</span>';
								break;
						}
						?>
						<div class="col-md-4">
							<p><b>Addresse de livraison :</b></p>
							<p> <?= $order->delivery_address ?></p>
							<p><b>Livreur :</b></p>
							<table style="width:100%; font-size:inherit;">
						<?php switch ($order->delivery_id) {
							case 1:
							echo '<tr>
									<td width="20%">
										<img src="/'. PROJECT_DIRECTORY .'/public/img/la-poste.png" height="50">
									</td>
									<td>
										La poste	
									</td>
									<td width="40%">
										7 jours
									</td>
									<td>
										1,50 	€	
									</td>
								</tr>';
								break;
							case 2: 
							echo '<tr>
									<td width="20%">
										<img src="/'.  PROJECT_DIRECTORY .'/public/img/colissimo.png" height="50">
									</td>
									<td>
										Colissimo
									</td>
									<td width="40%">
										Livraison en 2/3 jours ouvrés maximum	
									</td>
									<td>
										5,40 €	
									</td>
								</tr>';
								break;
							case 3:
							echo '<tr>
									<td width="20%">
										<img src="/'. PROJECT_DIRECTORY .'/public/img/chronopost.png" width="130">
									</td>
									<td>
										Chronopost
									</td>
									<td width="40%">
										Livraison en 24H	
									</td>
										<td>
										10,60 €	
									</td>
								</tr>';
							break;
						} ?>		
						</table>
						<br>
						<div class="col-md-12">
							<select class="form-control	">
								<option <?php if ($order->status_id == 0): echo 'selected'; endif; ?>value="0">En cours</option>
								<option <?php if ($order->status_id == 1): echo 'selected'; endif; ?>value="1">Envoyée</option>
								<option <?php if ($order->status_id == 2): echo 'selected'; endif; ?>value="2">Reçue</option>
								<option <?php if ($order->status_id == 3): echo 'selected'; endif; ?>value="3">Annulée</option>
							</select>
						</div>
						</div>
						<div class="col-md-7 col-md-offset-1">
							<table class="table">
								<tr>
								   	<td><img height="150" src="<?= get_avatar($pdt->content_image) ?>"></td>
								   	<td><h4><?= $pdt->content_title ?></h4></td>
								   	<td>x<?=$order->quantity ?> </td>
								   	<td><?= $price ?> €</td>
								   	<td><?= $status ?></td>
								</tr>
							</table>
						</div>
						
					</div>

     
			</div>
		</div>
	</div>
</div>
<?php include_once("footer.phtml"); ?>