<?php include_once("header.phtml"); ?>
<?php include_once("breadcrumb.phtml"); ?>
<?php
	$u = $Users[0];
?>
<div id="main-wrapper">
		<div class="profile-user">
			<div class="profile-cover">
	            <div class="row">
	                <div class="col-md-3 profile-image">
	                    <div class="profile-image-container">
	                        <img src="<?= $u->avatar ? "/" . PROJECT_DIRECTORY . $u->avatar : FRONT_IMG_PATH . "default_avatar.gif" ?>" alt="">
	                    </div>
	                </div>
	            </div>
	        </div>
	        <div id="main-wrapper">
	            <div class="row">
	                <div class="col-md-3 user-profile">
	                    <h3 class="text-center"><?= $u->first_name && $u->last_name ? $u->first_name . " " . $u->last_name : $u->login ?></h3>
	                    <hr>
	                    <ul class="list-unstyled text-center">
	                        <li><p><i class="fa fa-map-marker m-r-xs"></i>
	                        	<?php 
	                        		$completAddress = $u->address1 && $u->address2 ? $u->address1 . " / " . $u->address2 : "Adresse non renseignée";
	                        		$completAddress .= "<br>";
	                        		$completAddress .= $u->postal_code && $u->city ? $u->postal_code . " " . $u->city : "";
	                        		$completAddress .= $u->postal_code && $u->city && $u->country ? ", " : "";
	                        		$completAddress .= $u->country ? $u->country : "";
	                        		echo $completAddress;
	                        	?>
	                        </p>
	                        </li>
	                        <li><p><i class="fa fa-envelope m-r-xs"></i><a href="mailto:<?= $u->email ?>"><?= $u->email ?></a></p></li>
	                        <?php if($_SESSION['user']->role_id == 1 || $_SESSION['user']->role_id == 2) { ?>
	                        	<li><a href="/<?= PROJECT_DIRECTORY ?>dashboard/user/edit/<?= $u->id ?>">Modifier cet utilisateur</a></li>
	                        <?php } ?>
	                    </ul>
	                </div>
	                <div class="col-md-6 m-t-lg">
	                </div>
	                <div class="col-md-3 m-t-lg">
	                </div>
	            </div>
	        </div>
		</div>
</div><!-- Main Wrapper -->
<?php include_once("footer.phtml"); ?>