<?php 

if(is_url_dashboard()) {
include_once("header.phtml");  
} else {
include_once("frontheader.phtml");  
} ?>
<div id="content-wrapper" class="page page404">
	<div class="container">
		<div class="row">
			<h1>404</h1>
			<p>
			La page demandée n'existe pas
			</p>
		</div>
	</div>
</div>
<?php if(strstr( $_SERVER['REQUEST_URI'],'dashboard')) {
include_once("frontfooter.phtml");  
} else {
include_once("footer.phtml");  
} ?>