<?php


$produit = array();
$i = 0;

$db = new \config\database();

$query = 'SELECT c.*, ft.*, fp.*, c.id AS content_id, t.*, t.id AS content_type_id FROM `content` c
JOIN `content_type` t ON c.content_type_name = t.name
JOIN `field_title` ft ON c.id = ft.content_id
JOIN `field_price` fp ON c.id = fp.content_id
WHERE c.`content_type_name` = \'product\' AND c.id = 4';
$results = $db->query($query);

foreach($results as $produits)
{
    $produit[$i]['id'] = $produits->content_id;
    $produit[$i]['title'] = $produits->content_title;
    $produit[$i]['price'] = $produits->content_price;
    $i++;
}

var_dump($produit);

?>