<?php 
include_once("frontheader.phtml"); ?>
	  <!-- CONTENT -->
		<div id="content-wrapper">
			<div class="container">
				<div class="row">
					<h2>Meilleures ventes</h2>
					<hr>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-1.jpg" alt="DES CHATS !">
						</a>
					</div>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-4.jpg" alt="DES CHATS !">
						</a>
					</div>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-9.jpg" alt="DES CHATS !">
						</a>
					</div>
				</div>
				<div class="row">
					<h2>Nouveautés</h2>
					<hr>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-1.jpg" alt="DES CHATS !">
						</a>
					</div>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-4.jpg" alt="DES CHATS !">
						</a>
					</div>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-9.jpg" alt="DES CHATS !">
						</a>
					</div>
				</div>
				<div class="row">
					<h2>Prochaines ventes</h2>
					<hr>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-1.jpg" alt="DES CHATS !">
						</a>
					</div>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-4.jpg" alt="DES CHATS !">
						</a>
					</div>
					<div class="col-md-4">
						<a href="#">
							<img class="img-responsive" src="<?= FRONT_IMG_PATH ?>cats-q-c-600-600-9.jpg" alt="DES CHATS !">
						</a>
					</div>
				</div>
			</div>
			<hr>
		</div>
		<!-- END CONTENT -->

<?php include_once("frontfooter.phtml"); ?>