<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h3>Enregistrer un nouveau produit</h3>
            <hr>
            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/product/insert" method="post" class="form-horizontal">
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Titre</label>
                    <div class="col-sm-10"><input type="text" class="form-control" name="title"></div>
                </div>
                <div class="form-group">
                    <label for="category" class="col-sm-2 control-label">Catégorie</label>
                    <div class="col-sm-10">
                    <select name="category" class="form-control">
                        <option value="1">Mobilier</option>
                        <option value="2">Nourriture</option>
                        <option value="3">Informatique</option>
                    </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10"><textarea name="description" class="form-control" rows="5"></textarea></div>
                </div>
                <div class="form-group">
                    <label for="stock" class="col-sm-2 control-label">Stock</label>
                    <div class="col-sm-10"><input type="text" class="form-control" name="stock"></div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-2 control-label">Prix</label>
                    <div class="col-sm-10"><input type="text" class="form-control" name="price"></div>
                </div>
                <div class="form-group">
                    <label for="image" class="col-sm-2 control-label">Image</label>
                    <div class="col-sm-10"><input type="text" class="form-control" name="image"></div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Ajouter le produit</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>