<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); 
?>            
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">Ajouter un champ</h4>
                    </div>
					<div class="panel-body">
			            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/fields/insert" method="post" class="form-horizontal">
			                <div class="form-group">
			                    <label for="label" class="col-sm-2 control-label">Label</label>
			                    <div class="col-sm-10"><input type="text" class="form-control" name="label"></div>
			                </div>
                            <div class="form-group">
			                    <label for="name" class="col-sm-2 control-label">Identifiant du champ</label>
			                    <div class="col-sm-10">field_<input type="text" class="form-control" name="name"></div>
			                </div>
                            <div class="form-group">
			                    <label for="type" class="col-sm-2 control-label">Type</label>
			                    <div class="col-sm-10">
                                    <select class="form-control" name="type" onchange="selectshow(this);">
                                    <option value="input_text">Champ texte</option>
                                    <option value="textarea">Textarea</option>
                                    <option value="select">Liste</option>
                                    </select>
                                </div>
			                </div>
                            <div class="form-group" id="contenu-select">
			                    <label for="contenuselect" class="col-sm-2 control-label">Label</label>
			                    <div class="col-sm-10"><textarea class="form-control" name="contenuselect"></textarea></div>
			                </div>
			                <div class="form-group">
			                    <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Ajouter le champ</button></div>
			                </div>
			            </form>
					</div>
                </div>
			</div>
        </div>
    </div>
<?php include_once("footer.phtml"); ?>