<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); 
?>            
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">Informations principales</h4>
                    </div>
					<div class="panel-body">
			            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/page/insert" method="post" class="form-horizontal">
			                <div class="form-group">
			                    <label for="title" class="col-sm-2 control-label">Titre</label>
			                    <div class="col-sm-10"><input type="text" class="form-control" name="title"></div>
			                </div>
			                <div class="form-group">
			                    <label for="body" class="col-sm-2 control-label">Contenu</label>
			                    <div class="col-sm-10"><textarea name="body" class="form-control ckeditor" rows="5"></textarea></div>
			                </div>
			                <div class="form-group">
			                    <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Ajouter la page</button></div>
			                </div>
			            </form>
					</div>
                </div>
			</div>
        </div>
    </div>
<?php include_once("footer.phtml"); ?>