<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php $r = $Contents[0]; ?>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title">Supprimer un commentaire</h4>
                </div>
				<div class="panel-body">
                    
                <form action="/<?= PROJECT_DIRECTORY ?>dashboard/review/remove" method="post" class="form-horizontal">
                    
                    <?php $date = new DateTime($r->datecreated); ?>
                    <p>Posté par <em><?php print $r->login; ?></em> le <strong><?php print $date->format('d/m/Y à H:i'); ?></strong></p>
                    <p>Commentaire : <?php print $r->comment; ?></p>
                    <p>Score : <?php print $r->score; ?></p>
                    <div class="form-group">
                        <input type="hidden" name="id" value="<?php print $r->id; ?>">
                        <div class="col-sm-offset-3 col-sm-9"><button type="submit" class="btn btn-primary">Supprimer</button></div>
                    </div>
                 </form>
                    
			     </div>
            </div>
        </div>
    </div>
</div>
	
<?php include_once("footer.phtml"); ?>