<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php $c = $Contents[0]; ?>
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">Modifier une page</h4>
                    </div>
					<div class="panel-body">
			            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/page/update" method="post" class="form-horizontal">
			                <div class="form-group">
			                    <label for="title" class="col-sm-1 control-label">Titre</label>
			                    <div class="col-sm-11"><input value="<?php print $c->content_title; ?>" type="text" class="form-control" name="title"></div>
			                </div>
			                <div class="form-group">
			                    <label for="body" class="col-sm-1 control-label">Contenu</label>
			                    <div class="col-sm-11"><textarea name="body" class="form-control editor" rows="5"><?php print $c->content_body; ?></textarea></div>
			                </div>
			                <input type="hidden" name="content_id" value="<?php print $c->content_id; ?>">
			                <div class="form-group">
			                    <div class="col-sm-offset-1 col-sm-11">
			                    <button type="submit" class="btn btn-primary">Sauvegarder</button>
								</div>
			                </div>
			            </form>
					</div>
		        </div>
		    </div>
		</div>
	</div>
	
<?php include_once("footer.phtml"); ?>