<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>

<?php
$c = $Contents[0];

if($c->type == 'select') {
    $style = 'style="display:block;"';
} else {
    $style = '';
}
?>

	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title">Modifier un champ (<?php print $c->name.' - '.$c->type; ?>)</h4>
                    </div>
					<div class="panel-body">
			            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/fields/update" method="post" class="form-horizontal">
			                <div class="form-group">
			                    <label for="label" class="col-sm-2 control-label">Label</label>
			                    <div class="col-sm-10"><input type="text" class="form-control" value="<?php print $c->label; ?>" name="label"></div>
			                </div>
                            
                            <div class="form-group" id="contenu-select" <?php print $style; ?>>
			                    <label for="contenuselect" class="col-sm-2 control-label">Label</label>
			                    <div class="col-sm-10">
                                    <textarea class="form-control" name="contenuselect"><?php foreach($Contents[1] as $select){ print $select->name; } ?></textarea>
                                </div>
			                </div>
			                <div class="form-group">
			                    <div class="col-sm-offset-2 col-sm-10">
                                    <input type="hidden" value="<?php print $c->id; ?>" name="id">
                                    <input type="hidden" value="<?php print $c->name; ?>" name="name">
                                    <input type="hidden" value="<?php print $c->type; ?>" name="type">
                                    <button type="submit" class="btn btn-primary">Modifier le champ</button></div>
			                </div>
			            </form>
					</div>
                </div>
			</div>
        </div>
    </div>
<?php include_once("footer.phtml"); ?>