<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php $c = $Contents['results'][0]; ?>
<pre><?php print_r($c); ?></pre>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h3>Editer un produit</h3>
            <hr>
            <form action="/<?= PROJECT_DIRECTORY ?>dashboard/product/update" method="post" class="form-horizontal">
                
                <?php foreach($Contents['fields'] as $fields): ?>
                
                <?php
                    $type = $fields[0]->type;
                    $name = substr(strstr($fields[0]->name, '_'), 1);
                ?>
                
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label"><?php print $fields[0]->label; ?></label>
                    <div class="col-sm-10"><?php print $Content->contentModel->printField($type, $name, $c->{'content_'.$name}, 10, 100); ?></div>
                </div>
                
                <?php endforeach; ?>
                
                <input type="hidden" name="content_id" value="<?php print $c->content_id; ?>">
                
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Modifier le produit</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>