<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php
    $c = $Contents['results'][0]; 
    $tags_exists = array_key_exists('tags', $c);
?>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title">Editer un produit</h4>
                </div>
                <div class="panel-body">
                    <form action="/<?= PROJECT_DIRECTORY ?>dashboard/product/update" method="post" class="form-horizontal" enctype="multipart/form-data">
                        
                        <?php foreach($Contents['fields'] as $fields): ?>
                        
                        <?php
                        	$options = array();
                            $type = $fields[0]->type;
                            $name = substr(strstr($fields[0]->name, '_'), 1);
                            if($name == 'category'){
                            	$value = $c->{'content_'.$name};
                                $options = $Content->contentModel->AllCategory();
                            } else {
                                if($type == 'select'){
                                    $options = $Content->contentModel->getContentSelect('field_'.$name);
                                    $value = $c->{'content_'.$name};
                                } else {
                                    $value = $c->{'content_'.$name};
                                }
                            }
                            if ($name == 'image' && $value != '') {
        	                    echo '<div class="miniature col-sm-offset-2"><img src="/'.PROJECT_DIRECTORY.$c->{'content_'.$name}.'"></div><input type="hidden" name="old_image" value="'.$c->{'content_'.$name}.'">';
                            }
                        ?>
                        
                        <div class="form-group">
                            <label for="title" class="col-sm-2 control-label"><?php print $fields[0]->label; ?></label>
                            <div class="col-sm-10"><?php print $Content->contentModel->printField($type, $name, $value, 10, 100, $options); ?></div>
                        </div>
                        
                        <?php endforeach; ?>

                        <div class="form-group">
                            <label for="tag" class="col-sm-2 control-label">Tags</label>
                            <div class="col-sm-10"><input name="tag" class="form-control" row="5" value="<?= $tags_exists ? str_replace(",", ", ", $c->tags) : '' ?>"></div>
                            <small>Les tags doivent être séparés par des virgules.</small>
                        </div>
                        
                        <input type="hidden" name="content_id" value="<?php print $c->content_id; ?>">
                        
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10"><button type="submit" class="btn btn-primary">Sauvegarder</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>