<?php include_once("frontheader.phtml"); ?>
<?php
	$tag = $Contents[0]->name;
?>
	  <!-- CONTENT -->
		<div id="content-wrapper" class="content">
			<div class="container">
				<div class="row">
					<div class="col-md-12" id="article_list">
						<h1>Les contenus du tag "<?= $tag ?>"</h1>
						<?php
							end($Contents);
							$last = key($Contents);

							foreach ($Contents as $k => $c) {
								$row = "<div class='content_row'>";
								$row .= "<h2><a href='/" . PROJECT_DIRECTORY . $c->content_type_name . "/" . $c->content_id . "'>" . $c->content_title . "</a></h2>";
								$row .= "<small>" . ucfirst($c->content_type_name) . "</small>";
								if ($c->content_type_name == 'product') {
									$row .= "<p>" . $c->description . "</p>";
								} else {
									$row .= "<p>" . $c->body . "</p>";									
								}
								$row .= "<p><a href='/" . PROJECT_DIRECTORY . $c->content_type_name . "/" . $c->content_id . "'>Voir ce contenu</a></p>";
								if (!($k == $last)) {
									$row .= "<hr>";
								}
								$row .= "</div>";
								echo $row;
							}
						?>
					</div>
				</div>
			</div>
		</div>
<?php include_once("frontfooter.phtml"); ?>