<?php include_once("frontheader.phtml"); ?>
	  	<!-- CONTENT -->
		<div id="content-wrapper" class="product">
			<div class="container">
				<div class="row">
					<div class="col-md-12" id="product_list">
						<h1>Les produits</h1>
						<div class="button-group filters-button-group">
						  <button class="button is-checked" data-filter="*">Tous</button>
						  <?php
						  	$categories = $Content->contentModel->AllCategory();

						  	foreach ($categories as $c) {
						  		echo "<button class='button btn-filter' data-filter='." . strtolower($c->name) . "'>" . ucfirst($c->name) . "</button>";
						  	}
						  ?>
						</div>

						<div class="grid">
						<?php
							foreach ($Contents as $k => $p) {
								$image = $p->content_image ? "/" . PROJECT_DIRECTORY . $p->content_image : FRONT_IMG_PATH . "default-image.png";
								$row = "<div class='p_row " . strtolower($p->category_name) . " data-category=" . strtolower($p->category_name) . "'>";
								$row .= "<div class='product_photo'>";
								$row .= "<img src='" . $image . "' alt='" . $p->content_title . "'>";
								$row .= "</div>";
								$row .= "<div class='product_details'>";
								$row .= "<a href='/" . PROJECT_DIRECTORY . "product/".$p->content_id."'></a>";
								$row .= "<h2>" . $p->content_title . "</h2>";
								$row .= "<small>Proposé par " . $p->user_login . "</small>";
								$row .= "<div><span class='green'>Prix :</span> " . $p->content_price . " €</div>";
								$row .= "<div><span class='green'>Stock :</span> " . $p->content_stock . "</div>";
								$row .= "</div>";
								$row .= "</div>";
								echo $row;
							}
						?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			$( function() {

			  // init Isotope
			  var $grid = $('.grid').isotope({
			    itemSelector: '.p_row',
			    layoutMode: 'fitRows'
			  });

			  // bind filter button click
			  $('.filters-button-group').on( 'click', 'button', function() {
			    var filterValue = $( this ).attr('data-filter');
			    $grid.isotope({ filter: filterValue });
			  });

			  // change is-checked class on buttons
			  $('.button-group').each( function( i, buttonGroup ) {
			    var $buttonGroup = $( buttonGroup );
			    $buttonGroup.on( 'click', 'button', function() {
			      $buttonGroup.find('.is-checked').removeClass('is-checked');
			      $( this ).addClass('is-checked');
			    });
			  });
			  
			});

		</script>
<?php include_once("frontfooter.phtml"); ?>