<?php include_once("frontheader.phtml"); 
	$p = $Contents['results'][0];
	$p_f = $Contents['fields'];
	$custom = array();
	foreach($p_f as $field) {
		if($field[0]->custom == 1) {
			$custom[] = $field[0];
		}
	}
	$image = $p->content_image ? "/" . PROJECT_DIRECTORY . $p->content_image : FRONT_IMG_PATH . "default-image.png";
	$user_content = $Content->contentModel->getContentByProduct($p->content_id);
	//var_dump($user_content);
?>
	  <!-- CONTENT -->
		<div id="content-wrapper" class="product">
			<div class="container">
				<?php include_once("frontbreadcrumb.phtml"); ?>
				<div class="row">
					<div class="col-md-12" id="product_view">
						<h1><?= $p->content_title ?></h1>
						<div class="col-md-6 product_image">
							<img src="<?= $image ?>">
							<a href="/<?= PROJECT_DIRECTORY; ?>product" >Retour à la liste des produits</a>
						</div>
						<div class="col-md-6">						
					
						<h3>Attributs</h3> 
						<div class="col-md-3">
                        	<b>Prix :</b>
                        </div>	
						<div class="col-md-9">
							<?= $p->content_price; ?> €
                        </div>

						<div class="col-md-3">
                        	<b>Catégorie :</b>
                        </div>	
						<div class="col-md-9">
							<?= $p->category_name; ?>
                        </div>

                        <div class="col-md-3">
                        	<b>Tags :</b>
                        </div>	
						<div class="col-md-9 label">
	                        <?php 
								if (isset($p->tagsView)) {
									echo str_replace(',', ', ', $p->tagsView);
								}
							?>
						</div>

						<div class="col-md-12">
                        	<b>Description :</b><br>
                        	<small>
								<?= $p->content_description ?>
							</small>
                        </div>	

                        <?php foreach($custom as $c) {
        
                                if($c->type == 'select') {
                                    $value = $Content->contentModel->getContentSelectValue($p->{str_replace('field_','content_',$c->name)});
                                    print '<div class="col-md-3"><b>'.$c->label .' :</b></div><div class="col-md-9"> '.$value[0]->name.'</div>';
                                } else {
                                    print '<div class="col-md-3"><b>'.$c->label .' :</b></div><div class="col-md-9"> '.$p->{str_replace('field_','content_',$c->name)}.'</div>';
                               }
        
	                    } ?>

						<a class="btn btn-add" href="/<?= PROJECT_DIRECTORY; ?>cart/add/<?=$p->content_id?>" >Ajouter au panier</a>
					</div>
					<div class='col-md-12'>
						<h2>Ce même produit est proposé par :</h2>
						<?php 
							foreach ($user_content as $v) {
								$p->content_price = $v->content_price;
								$row = "<div class='row'>";
								$row .= "<div class='col-md-4'>";
								$row .= "<p>" . $v->login . "</p>";
								$row .= "</div>";
								$row .= "<div class='col-md-4'>";
								$row .= "<p>À " . $v->content_price . " €</p>";
								$row .= "</div>";
								$row .= "<div class='col-md-4'>";
								$row .= "<a class='btn btn-add' href='/". PROJECT_DIRECTORY ."cart/add/" . $p->content_id . "' >Ajouter au panier</a>";
								$row .= "</div>";
								$row .= "</div>";
								echo $row;
							}
						?>
					</div>
				</div>
			</div>
		</div>
<?php include_once("frontfooter.phtml"); ?>