<?php include_once("frontheader.phtml"); 
	$page = $Contents[0]; 
?>
	  <!-- CONTENT -->
		<div id="content-wrapper" class="page">
			<div class="container">
				<?php include_once("frontbreadcrumb.phtml"); ?>
				<div class="row">
					<div class="col-md-12">
						<h1><?= $page->name ?></h1>
						<div class="grid">

						<?php foreach($page->products as $p) {
							$row = "<div class='p_row " . strtolower($p->category_name) . " data-category=" . strtolower($p->category_name) . "'>";
							$row .= "<div class='product_photo'>";
							$row .= '<img src="'.get_miniature($p->content_image).'" alt="">';
							$row .= "</div>";
							$row .= "<div class='product_details'>";
							$row .= "<a href='/" . PROJECT_DIRECTORY . "product/".$p->content_id."'></a>";
							$row .= "<h2>" . $p->content_title . "</h2>";
							$row .= "<small>Proposé par : " . $p->user_login . "</small>";
							$row .= "<div> " . $p->content_price . " €</div>";
							$row .= "</div>";
							$row .= "</div>";
							echo $row;
						} ?>
					</div>
					</div>
				</div>
			</div>
		</div>
<?php include_once("frontfooter.phtml"); ?>