<?php include_once("frontheader.phtml"); ?>
	<style type="text/css">
		.p_row {
			border: 1px solid #000;
			display: inline-block;
			height: 150px;
			margin: 35px;
			position: relative;
			width: 150px;
		}
		.p_row .product_photo,
		.p_row .product_details,
		.p_row .product_details a {
			height: 100%;
			position: absolute;
			width: 100%;
		}
		.p_row .product_details {
			opacity: 0;
			transition: all 300ms ease;
		}
		.p_row .product_details:hover {
			background-color: rgba(255, 255, 255, 0.8);
			opacity: 1;
		}
	</style>
	  	<!-- CONTENT -->
		<div id="content-wrapper" class="product">
			<div class="container">
				<div class="row">
					<div class="col-md-12" id="product_list">
						<h1>Les produits</h1>

						<div class="button-group filters-button-group">
						  <button class="button is-checked" data-filter="*">Tous</button>
						  <button class="button" data-filter=".nourriture">Nourriture</button>
						  <button class="button" data-filter=".informatique">Informatique</button>
						  <button class="button" data-filter=".mobilier">Mobilier</button>
						  <!-- PENSER A FAIRE UNE REQUETE POUR OBTENIR TOUTES LES CATEGORIES -->
						</div>

						<div class="grid">
						<?php
							foreach ($Contents as $k => $p) {
								$row = "<div class='p_row " . strtolower($p->category_name) . " data-category=" . strtolower($p->category_name) . "'>";
								$row .= "<div class='product_photo'>";
								$row .= "<img src='' alt=''>";
								$row .= "</div>";
								$row .= "<div class='product_details'>";
								$row .= "<a href='/" . PROJECT_DIRECTORY . "product/".$p->content_id."'></a>";
								$row .= "<h2>" . $p->content_title . "</h2>";
								$row .= "<small>Proposé par : " . $p->user_login . "</small>";
								$row .= "<div>Prix : " . $p->content_price . " €</div>";
								$row .= "<div>Stock : " . $p->content_stock . "</div>";
								$row .= "</div>";
								$row .= "</div>";
								echo $row;
							}
						?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			$( function() {

			  // init Isotope
			  var $grid = $('.grid').isotope({
			    itemSelector: '.p_row',
			    layoutMode: 'fitRows'
			  });

			  // bind filter button click
			  $('.filters-button-group').on( 'click', 'button', function() {
			    var filterValue = $( this ).attr('data-filter');
			    $grid.isotope({ filter: filterValue });
			  });

			  // change is-checked class on buttons
			  $('.button-group').each( function( i, buttonGroup ) {
			    var $buttonGroup = $( buttonGroup );
			    $buttonGroup.on( 'click', 'button', function() {
			      $buttonGroup.find('.is-checked').removeClass('is-checked');
			      $( this ).addClass('is-checked');
			    });
			  });
			  
			});

		</script>
<?php include_once("frontfooter.phtml"); ?>