<?php include_once("frontheader.phtml"); 
	$p = $Contents['results'][0]; 
?>
	  <!-- CONTENT -->
		<div id="content-wrapper" class="product">
			<div class="container">
				<div class="row">
					<div class="col-md-12" id="article_list">
						<h1><?= $p->content_title ?></h1>
						<small>
						<?= $p->content_description ?>
						</small>
						<a class="btn btn-add" href="/<?= PROJECT_DIRECTORY; ?>cart/add/<?=$p->content_id?>" >Ajouter au panier</a>
					</div>
				</div>
			</div>
		</div>
<?php include_once("frontfooter.phtml"); ?>