<?php include_once("frontheader.phtml"); ?>
<?php $fields = $Content->contentModel->getFieldsName("product"); ?>
	  <!-- CONTENT -->
		<div id="content-wrapper" class="article">
			<div class="container">
				<div class="row">
					<div class="col-md-6" id="product_add">
						<h1>Enregistrer un nouveau produit</h1>
			            <form action="/<?= PROJECT_DIRECTORY ?>product/insert" method="post" class="form-horizontal" enctype="multipart/form-data">
			                
			                <?php foreach($fields as $field): ?>
			                
                            <?php if(substr(strstr($field[0]->name, '_'), 1) != 'active') : ?>
                            
			                <?php
			                    $type = $field[0]->type;
			                    $name = substr(strstr($field[0]->name, '_'), 1);
			                    if($name == 'stock'){
				                    echo '<input type="hidden" name="stock" value="1">';
				                    continue;
			                    }
			                    if($name == 'category'){
                                    $options = $Content->contentModel->AllCategory();
                                    $value = '';
                                } else {
                                    if($type == 'select'){
                                        $options = $Content->contentModel->getContentSelect('field_'.$name);
                                        $value = '';
                                    } else {
                                        $options = '';
                                        $value = '';
                                    }
                                }
			                ?>
			                
			                <div class="form-group">
			                    <label for="title" class="col-sm-4 control-label"><?php print $field[0]->label; ?></label>
			                    <div class="col-sm-8"><?php print $Content->contentModel->printField($type, $name, $value, 10, 100, $options); ?></div>
			                </div>
                            
                            <?php endif; ?>
			                
			                <?php endforeach; ?>
			                
                            <input type="hidden" name="active" value="0">
                            
			                <div class="form-group">
			                    <div class="col-sm-offset-4 col-sm-8"><button type="submit" class="btn btn-primary">Ajouter le produit</button></div>
			                </div>
			            </form>
					</div>
                    
                    <div class="col-md-6" id="product_add_stock">
                        <h1>Vendre un produit déjà existant</h1>
                        <form action="/<?= PROJECT_DIRECTORY ?>dashboard/product/plus" method="post" class="form-horizontal" enctype="multipart/form-data">
                            <div class="form-group">
			                    <label for="id_product" class="col-sm-4 control-label">Produit</label>
			                    <div class="col-sm-8">
                                    <select name="id_product" class="form-control">
                                        <?php foreach($Contents as $product) : ?>
                                            <option value="<?php print $product->content_id; ?>"><?php print $product->content_title; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
			                </div>
                            <div class="form-group">
			                    <label for="price" class="col-sm-4 control-label">Votre prix</label>
			                    <div class="col-sm-8"><input type="text" name="price" class="form-control"></div>
			                </div>
                            <div class="form-group">
			                    <div class="col-sm-offset-4 col-sm-8"><button type="submit" class="btn btn-primary">Ajouter le produit</button></div>
			                </div>
                        </form>
                    </div>
                    
				</div>
			</div>
		</div>
<?php include_once("frontfooter.phtml"); ?>