<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<?php $types = array('input_text' => 'Champ texte', 'select' => 'Liste'); ?>

<div id="main-wrapper">
    <div class="col-lg-12 col-md-12">
        <div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Gestion des champs supplémentaires</h4>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">
                    <p><a href="fields/add"><button type="button" class="btn btn-primary">Ajouter un champ</button></a></p>
                    <table class="table listtable">
                        <tr>
                            <th>Label</th>
                            <th>Type</th>
                            <th></th>
                            <th></th>
                        </tr>
                        <?php foreach($Contents as $field): ?>

                        <tr>
                            <td><?php print $field->label; ?></td>
                            <td><?php print $types[$field->type]; ?></td>
                            <td class='action'><a href="fields/edit/<?php print $field->id; ?>"><span class='fa fa-pencil-square-o'></span></a></td>
                            <td class='action'><a href="fields/delete/<?php print $field->id; ?>"><span class='fa fa-times'></span></a></td>
                        </tr>

                        <?php endforeach; ?>
                    </table>
                </div>
			</div>
		</div>
	</div>
</div>

<?php include_once("footer.phtml"); ?>