<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
   	<div class="row">
	    <div class="col-lg-12 col-md-12">
			<div class="panel panel-white">
				<div class="panel-heading">
					<h4 class="panel-title">Les pages</h4>
				</div>
				<div class="panel-body">
					<div class="table-responsive list-user">
                   <p><a href="page/add"><button type="button" class="btn btn-primary">Ajouter une page</button></a></p>
                    	<table class="table listtable">
							<thead>
								<tr>
									<th>Titre</th>
									<th></th>
									<th></th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<?php
									foreach ($Contents as $Page) {
										$row = '';
										$row .= "<th>" . $Page->content_title . "</th>";
										$row .= "<td class='action'><a href='/" . PROJECT_DIRECTORY . "dashboard/page/".$Page->content_id."'><span class='fa fa-plus-square-o'></span></a></td>";
										$row .= "<td class='action'><a href='/" . PROJECT_DIRECTORY . "dashboard/page/edit/".$Page->content_id."'><span class='fa fa-pencil-square-o'></span></a></td>";
										$row .= "<td class='action'><a href='/" . PROJECT_DIRECTORY . "dashboard/page/delete/".$Page->content_id."'><span class='fa fa-times'></span></a></td></tr>";
										$row .= "</tr>";
										echo $row;
	
									}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
   	</div>
</div>

<?php include_once("footer.phtml"); ?>