<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
    <div class="col-lg-12 col-md-12">
        <div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Gestion des champs supplémentaires</h4>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">
                    <table>
                        <tr>
                            <th>Label</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        <?php foreach($Contents as $field): ?>

                        <tr>
                            <td><?php print $field->label; ?></td>
                            <td><a href="<?php print PROJECT_DIRECTORY; ?>dashboard/product/<?php print $field->id; ?>"><span class='fa fa-plus-square-o'></span></a></td>
                            <td><a href="<?php print PROJECT_DIRECTORY; ?>dashboard/product/edit/<?php print $field->id; ?>"><span class='fa fa-pencil-square-o'></span></a></td>
                            <td><a href="<?php print PROJECT_DIRECTORY; ?>dashboard/product/delete/<?php print $field->id; ?>"><span class='fa fa-times'></span></a></td>
                        </tr>

                        <?php endforeach; ?>
                    </table>
                </div>
			</div>
		</div>
	</div>
</div>

<?php include_once("footer.phtml"); ?>