<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>
<div id="main-wrapper">
    <div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h4 class="panel-title">Les articles</h4>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">  
					<table class="table">
						<thead>
							<tr>
								<th>Titre</th>
								<th>Contenu</th>
								<th>Date de création</th>
								<th>Créé par</th>
								<th></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach ($Contents as $Article) {
									$created_by = $Article->first_name && $Article->last_name ? $Article->first_name . " " . $Article->last_name : $Article->login;
									$row = "<tr>";
									$row .= "<th><a href='/" . PROJECT_DIRECTORY . "dashboard/article/".$Article->content_id."'>" . $Article->content_title . "</a></th>";
									$row .= "<td>" . $Article->content_body . "</td>";
									$row .= "<td>" . $Article->created_date . "</td>";
									$row .= "<td>" . $created_by . "</td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/article/".$Article->content_id."'><span class='fa fa-plus-square-o'></span></a></td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/article/edit/".$Article->content_id."'><span class='fa fa-pencil-square-o'></span></a></td>";
									$row .= "<td><a onclick='myFunction(".$Article->content_id.")'><span class='fa fa-times'></span></a></td></tr>";
									$row .= "</tr>";
									echo $row;
								}
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function myFunction(id) {
	    if(confirm("Etes-vous sûr de vouloir supprimer cet article ? Cette action est irréversible.")) {
	    	window.location = "article/delete/"+id;
		}
	}
</script>
<?php include_once("footer.phtml"); ?>