<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
    <div class="col-lg-12 col-md-12">
		<div class="panel panel-white">
			<div class="panel-heading">
				<h3 class="panel-title">Les produits</h3>
			</div>
			<div class="panel-body">
				<div class="table-responsive list-user">  
					<table class="table">
						<thead>
							<tr>
								<th>Titre</th>
								<th>Catégorie</th>
								<th>Prix</th>
								<th>Stock</th>
								<th></th>
								<th></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach ($Contents as $Product) {

									if($Product->content_stock == 0) {
										$row = "<tr class=\"danger\">";
									} else {
										$row = "<tr>";
									}
                                    
                                    $category = $Content->contentModel->getCategory($Product->content_category);

									$row .= "<th><a href='/" . PROJECT_DIRECTORY . "dashboard/product/".$Product->content_id."'>" . $Product->content_title . "</a></th>";
                                    $row .= "<td>" . $category[0]->name . "</td>";
									$row .= "<td>" . $Product->content_price. " €</td>";
									$row .= "<td>" . $Product->content_stock . "</td>";
									$row .= "<td style='text-align:center'>".($Product->content_active == 1 ? '<span class="label label-success">Validé</span>' : '<span class="label label-danger">Non validé</span>')." </td>";

									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/product/".$Product->content_id."'><span class='fa fa-plus-square-o'></span></a></td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/product/edit/".$Product->content_id."'><span class='fa fa-pencil-square-o'></span></a></td>";
									$row .= "<td><a href='/" . PROJECT_DIRECTORY . "dashboard/product/delete/".$Product->content_id."'><span class='fa fa-times'></span></a></td></tr>";
									$row .= "</tr>";
									echo $row;

								}
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<?php include_once("footer.phtml"); ?>