<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>  
<?php
    $c = $Contents[0];
?>          
<div id="main-wrapper">
    <div class="col-lg-12">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h4><?= $c->content_title ?></h4>
                <small><?= $c->created_date ?></small>
            </div>
            <div class="panel-body">
                <img alt="<?= $c->content_title ?>" src="<?= "/" . PROJECT_DIRECTORY . $c->content_image ?>">
                <p><?= $c->content_body ?></p>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>