<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
    <div class="row">
		<div id="main-wrapper">
			<div class="col-lg-12 col-md-12">
				<div class="panel panel-white">
					<div class="panel-heading">
						<h4 class="panel-title"><?php print $Contents[0]->content_title; ?></h4>
					</div>
					<div class="panel-body">
		            <p><?php print $Contents[0]->content_body; ?></p>
		            <p>
	                    <a class="btn btn-primary" href="<?= '/' . PROJECT_DIRECTORY . 'dashboard/page/edit/' . $Contents[0]->content_id ?>">Modifier ce contenu</a>
	                </p>
					</div>
				</div>
		    </div>
		</div>
	</div>
</div>
<?php include_once("footer.phtml"); ?>