<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); 
	$product = $Contents['results'][0];
	$product_fields = $Contents['fields'];
	$r = $Contents['review'];
	$custom = array();
	foreach($product_fields as $field) {
		if($field[0]->custom == 1) {
			$custom[] = $field[0];
		}
	}
	$image = $product->content_image ? "/" . PROJECT_DIRECTORY . $product->content_image : FRONT_IMG_PATH . "default-image.png";
	$tags_exists = array_key_exists('tags', $product);
?>            
	<div id="main-wrapper">
		<div class="row">
			<div class="col-md-12">
                <div class="panel panel-white" id="back_product_view">
                    <div class="panel-heading clearfix">
                        <h3 class="panel-title ">
                        	<?= $product->content_title; ?>
                        </h3>
                    </div>
					<div class="panel-body">
					<div class="col-md-6 product_image"><img src="<?= $image ?>"></div>
					<div class="col-md-6 product_details">						
					
						<h3>Attributs</h3> 
						<div class="col-md-3">
                        	<b>Prix :</b>
                        </div>	
						<div class="col-md-9">
							<?= $product->content_price; ?> €
                        </div>

						<div class="col-md-3">
                        	<b>Catégorie :</b>
                        </div>	
						<div class="col-md-9">
							<?= $product->category_name; ?>
                        </div>

                        <div class="col-md-3">
                        	<b>Tags :</b>
                        </div>	
						<div class="col-md-9 label">
							<?php
								if($tags_exists) { 
									echo str_replace(',', ', ', $product->tags);
								} else {
									echo "Pas de tags associés";
								}
							?>
                        </div>

						<div class="col-md-12">
                        	<b>Description :</b>
                        </div>	
						<div class="col-md-12">
							<?= $product->content_description; ?>
                        </div>

						<?php foreach($custom as $c) {
                            if($c->type == 'select') {
                                $value = $Content->contentModel->getContentSelectValue($product->{str_replace('field_','content_',$c->name)});
                                print '<div class="col-md-3"><b>'.$c->label .' :</b></div><div class="col-md-9"> '.$value[0]->name.'</div>';
                            } else {
                                print '<div class="col-md-3"><b>'.$c->label .' :</b></div><div class="col-md-9"> '.$product->{str_replace('field_','content_',$c->name)}.'</div>';
                           }        
	                    } ?>
	                    <div class="col-md-12">
	                    	<a class="btn btn-primary" href="<?= '/' . PROJECT_DIRECTORY . 'dashboard/product/edit/' . $product->content_id ?>">Modifier ce contenu</a>
	                    </div>
			          	</div>
					</div>
                </div>
			</div>
        </div>
        <?php if(!empty($r)) : ?>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped list-comment">
                    <th>Auteur</th>
                    <th>Note</th>
                    <th>Commentaire</th>
                    <th></th>
                    <th></th>
                <?php foreach($r as $review) : ?>
                <?php $date = new DateTime($review->datecreated); ?>
                    <tr>
                        <td><?php print $review->login; ?> (<?php print $date->format('d/m/Y à H:i'); ?>)</td>
                        <td><input type="hidden" class="rating" value="<?php print $review->score; ?>" data-readonly/></td>
                        <td><?php print substr($review->comment, 0, 20); ?> ...</td>
                        <td><a href="/<?php print PROJECT_DIRECTORY ; ?>dashboard/review/edit/<?php print $review->id; ?>"><span class="fa fa-pencil-square-o"></span></a></td>
						<td><a href="/<?php print PROJECT_DIRECTORY ; ?>dashboard/review/delete/<?php print $review->id; ?>"><span class="fa fa-times"></span></a></td>
                    </tr>
                <?php endforeach; ?>
                </table>
            </div>
        </div>
        <?php else : ?>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <p>Aucun commentaire pour le moment.</p>
            </div>
        </div>
        <?php endif; ?>
    </div>
<?php include_once("footer.phtml"); ?>