<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>            
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            <h2><?php print $Contents['results'][0]->content_title; ?></h2>
            <h3><span class="glyphicon glyphicon-euro" aria-hidden="true"></span> <?php print $Contents['results'][0]->content_price; ?></h3>
            <?php if($Contents['results'][0]->content_stock > 0): ?>
                <h3><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> <?php print $Contents['results'][0]->content_stock; ?></h3>
            <?php else: ?>
                <h3><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> <span class="text-danger"><?php print $Contents['results'][0]->content_stock; ?></span></h3>
            <?php endif; ?>
        </div>
        <div class="col-md-6">
            <h2>Description</h2>
            <p><?php print $Contents['results'][0]->content_description; ?></p>
        </div>
    </div>
    <?php $custom = $Content->contentModel->getFieldList(); ?>
    <?php if(!empty($custom)): ?>
        <?php foreach($custom as $field): ?>
        <?php $fieldname = substr(strstr($field->name, '_'), 1);
        $value = 'content_'.$fieldname; ?>
        <div class="row">
            <div class="col-md-3">
                <h3><?php print $field->label; ?></h3>
            </div>
            <div class="col-md-9">
                <p><?php print $Contents['results'][0]->$value; ?></p>
            </div>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php include_once("footer.phtml"); ?>