<?php include_once("admin/header.phtml"); ?>
<?php include_once("admin/breadcrumb.phtml"); ?>  
<?php
    $c = $Contents[0];
    $tags_exists = array_key_exists('tags', $c);
    $created_by = $c->first_name && $c->last_name ? $c->first_name . " " . $c->last_name : $c->login;
?>          
<div id="main-wrapper">
    <div class="col-lg-12">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h4><?= $c->content_title ?></h4>
                <small><?= "Le " . $c->created_date . " par " . $created_by ?></small>
            </div>
            <div class="panel-body">
                <img alt="<?= $c->content_title ?>" src="<?= '/' . PROJECT_DIRECTORY . $c->content_image ?>">
                <p><?= $c->content_body ?></p>
                <?php if($tags_exists) { ?>
                    <small class="label"><?= str_replace(',', ', ', $c->tags) ?></small>
                <?php } ?>
                <p>
                    <a href="<?= '/' . PROJECT_DIRECTORY . 'dashboard/article/edit/' . $c->content_id ?>">Modifier ce contenu.</a>
                </p>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.phtml"); ?>